In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# pip install gensim
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
import numpy as np
np.random.seed(400)

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
df = pd.read_csv("/content/2021_Sep5_97k_hydrated_tweets.csv")

In [ ]:
df.drop(columns=['id_str',"in_reply_to_screen_name","is_retweet"], inplace=True)

In [ ]:
# Function to Clean the Tweet.

import re
def clean_tweet(tweet):
    return ' '.join(re.sub('(\\\\n)|(b\"[^0-9A-Za-z A-Za-z0-9 \t]+)|(b\'[^0-9A-Za-z]+)|(b\"[A-Za-z0-9]+)|(b\'[A-Za-z0-9]+)|(b\'#[A-Za-z0-9]+)|(b\'@[A-Za-z0-9]+)|(\\\\x[A-Za-z0-9]+)|(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|([RT])', ' ', str(tweet).lower()).split())

In [ ]:
# Call function to get Clean tweets
df["CleanTweet"] = df['text'].apply(lambda x : clean_tweet(x))
df.tail()

,favorite_count,source,text,created_at,retweet_count,CleanTweet
78210,0,PostBeyond,b'An online tool used by people in Italy to ma...,Mon Sep 06 04:02:23 +0000 2021,2,online tool used by people in italy to manage ...
78211,1,Khoros CX,"b""@seany_boy71 Hi there, it sounds like you're...",Mon Sep 06 04:02:28 +0000 2021,0,seany boy71 hi there it sounds like you re tal...
78212,0,Twitter Web App,b'@TracyBethHoeg REALLY? YOU THINK? GIVEN THER...,Mon Sep 06 04:02:23 +0000 2021,0,tracybethhoeg really you think given there is ...
78213,0,Twitter for iPhone,b'So in an area thats of \xe2\x80\x98major out...,Mon Sep 06 04:02:22 +0000 2021,0,in an area thats of outbreak concern they put ...
78214,0,Twitter for Android,b'@GovAbbott and State Republicans allowed my ...,Mon Sep 06 04:02:16 +0000 2021,0,govabbott and state republicans allowed my you...

In [ ]:
df.drop(df.index[df.CleanTweet.eq("")], inplace=True)

In [ ]:
df.head()

,favorite_count,source,text,created_at,retweet_count,CleanTweet
0,1,Twitter for Android,"b""Don't believe it. https://t.co/VFfhPArn1a""",Sat Sep 03 04:09:04 +0000 2022,0,t believe it
1,0,cmssocialservice,b'Surat records 11 new Covid-19 cases https://...,Sat Sep 03 04:06:03 +0000 2022,0,records 11 new covid 19 cases
2,38,TweetDeck,b'Hennepin County will no longer require COVID...,Sat Sep 03 04:09:00 +0000 2022,6,county will no longer require covid 19 vaccine...
3,2,Twitter Web App,"b'As of Sept 1, the capital has given over 63....",Sat Sep 03 04:08:52 +0000 2022,0,of sept 1 the capital has given over 63 2 mill...
4,1,Twitter for Android,b'@KushThrough @BlazedRTs @rtsmallstreams @Rts...,Sat Sep 03 04:15:46 +0000 2022,3,kushthrough ww nowplaying x lilroyce her ev

In [ ]:
stemmer = SnowballStemmer(language='english')
def lemmatize_stemming(text):
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))

# Tokenize and lemmatize
def preprocess(text):
    result=[]
    for token in gensim.utils.simple_preprocess(text) :
        if token not in gensim.parsing.preprocessing.STOPWORDS and len(token) > 3:
            result.append(lemmatize_stemming(token))
            
    return result

In [ ]:
complete_text = ' '.join(df["CleanTweet"])

In [ ]:
data = df.CleanTweet.values.tolist()

In [ ]:
pprint(data[:2])

['t believe it', 'records 11 new covid 19 cases']

In [ ]:
complete_text

't believe it records 11 new covid 19 cases county will no longer require covid 19 vaccines for its employees of sept 1 the capital has given over 63 2 million doses of covid19 vaccines to over 23 6 million people kushthrough ww nowplaying x lilroyce her ev can t be good for you themixmedic nowplaying x lilroyce her evil spine feat makrazy total of 174 new cases of covid 19 were reported during the last 24 hours across the state odisha odishanews appointed by the israeli moh to investigate covid 19 vaccine side effects warned the ministry it could b covid 19 closed our campuses down the idea that every student has a computer a word processing program sta thetruthsucks12 why get poked in 2021 when covid 19 has a 98 survival rate got a bridge in brooklyn for sale yo federal government is fucking trash dubai reins in hospitality as covid 19 cases rise is hilarious you can make this up the camp counselor who tried to overturn a decisive democratic election pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri fucking idiots odisha reports 174 new cases of covid19 in the last 24 hours of which 0 18 years 13 in quarantine 102 local contacts 72 invented and cured coronavirus donald trump was very smart russia bombed the lab in ukraine that was genera not a way to handle the pandemic science table members disagree with scrapping 5 day covid 19 isolation cbc ne covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily positivity rate 1 98 in an almighty coronavirus metaphor at stechford baths station rd 19 or swine flu know how to differentiate between the geauxt17 had been in the house coronavirus task force for decades you said that right 19 journal for friday september 2 2022 records 46 new cases of coronavirus within 24 denise dewald wuhan used an unknown coronavirus test initially does argentina have access to this friday broadcast of the five fox news greg gutfeld proclaimed that he is disinformation after a co break on august 23 the botetourt county board of supervisors approved an additional 250 000 in personal pro deblvsbabygroot really does depend on the circumstances here is the workcover qld link profesterman thanks for the daily covid19 data amp i hope your dog maintains the waistline odisha covid19 report for 2nd sept new positive cases 174 of which 0 18 years 13 in quarantine 102 local c 6 months can now receive safe amp effective covid 19 vaccines talk to your child doctor amp help them is back in session but even before the first test has been given new numbers have confirmed what many teach that takes this murdering jab is just as stupid as you murderer make it stop america last is fucking with our country hard and they pull this shit again and again they xf0 assamese morning news hours 09 2022 covid19 covid19 could given that money to ukraine ashleigh roy but but you get a little excited clicking the link only to find it s a treatment you ve already tried amp didn t get mu can hear her now msmcmo trump had a cure for covid19 he said just inject disinfectant into your body covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours canmericanized if you believe that only 190 arrivecan tickets were issued since the app was made mandatory than y reptedbudd are you demanding answers from boss trump why he took top sci files why are 4 s time for our leaders to sit up pay attention and expand social security disability benefits to the millions world covid19 vaccine protection rates of 7 countries against infection in the delta amp omicron eras the avera reports first human case of west nile virus this survived covid 19 with them but we now loosing them to tumbwa records 11 new covid 19 cases blame bidentrump fuck them covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p president was just telling the god s truth you follow the evil liar con your trumpy con man demonized thous brendanjanus covid 19 vaccines available in the united states are safe and are effective a 28 2017 age 35 l 23rd last gs win vs sister age 36 9 2 22 pursuit of potus the lockdowns reduced mortality from covid 19 by just 0 2 those jobs should have never been lost in the first place happening in china this woman tried to take down jordan b peterson now she wants to take down her employer you would find the truth of the complete case file regarding the coronavirus from beginning to end imam mahdi n pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri big kristiiiii nowplaying x lilroyce her evil spine feat makrazy demise of society this administration is insane managed to beat covid19 for almost two years then one day newsom in laws moved to florida during the coronavirus hampshire covid 19 updates numbers for cases hospitalizations vaccinations 211 fresh covid 19 cases in india in the last 24 hours covid19 mask mandates are too much to ask for pres biden on covid 19 funds for local economies 2 after words sen tammy duckworth d il every day is a gift cdc director signs off on new covid 19 boosters quietly adds ivermectin to covid 19 treatment guidelines as antiviral therapy big league politics messiah s didthatchokeyou that s almost as stupid as getting the covid 19 vaccination new covid19 variants could emerge this winter the european union drug agency has said but existing va is stupid asean family newsfrommalaysia covid19 malaysia as 2 september 2022 confirmed cases 2 328 research pandemic telehealth utilization related to decrease opioid overdose riskgetting opioid utilizati t co tgmsvs5p8l covid 19 outbreak declared over at bethammi nursing home 3rd floor tbay thunderbay middaynews mumbai sees 402 new covid 19 cases as virus kills 3 mumbainews covid19 covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p i have contacted the clix as well your partner they said we don t have any problem the account is opened only y are living through an intense drought with water resources at all time low scientists may have found a way jon o90 why are you lying about this dems are saving lives republicans were against the gshodl brics also announce that americans are evil and project whatever problems they themselves c serehfas covid surely must be one of the most familiar medical pathogens ever studied by now if this is not ident administration has been shuffling money from other pockets to pay for the new shots after congress failed t another example of the laptop classes hypocrisy who wants to be he supported vaccine mandates and people lo sleepy look after yourself and don t overdo it on the caffeine covid19 socialdistancing emotionalconnection in our icu with frontal contusion gcs full absolutely doing fine for 5 days desaturated one day and his truly do have the biggest fucking joke of a government to coronavirus indian people are worst sufferer since 22 03 2020 crores of people affected lakhs of people di medicaldevice regulatory daily stories via icis cdnhealth covid19 your unique nft covid 19 colorful variant 6280 now do you already own nfts gracelp they may still be good for a couple months hk watch how great ex cop ce mr lee to use smokescreen of covid to curb freedom n surveillance little kids aged korea reports less than 80 000 new covid 19 cases covid19 southkorea arirang news california gov gavin newsom in laws moved to florida during the chinese coronavirus pandemic 2 0 realdailywire covid19 return to work rebound isn t creating jobs stop distorting the facts pushing inaccurate covid 19 boosters that target the most common omicron strains are set to begin soon 19 update 84 new covid 19 cases reported on september 2 uptown c the website says covid 19 vaccine update cdc now recommends the new updated tucson area coronavirus developments sept 3 what we know billion of tax payer money went to people in prison k datastudio tells us covid has been the 3 cause of death in canada for three years running and yeah county will no longer require covid 19 vaccines for its decontamination and cleaning of their patrol vehicle 66 to prevent the transmission of the deadly covid 1 demands rs 1 000 crore from covid 19 vaccine makers for daughter s death bombay hc issues notice to sii bill friendlycovid19 it s a booster so what doesn t mean the people won t get a visit from our friendly neighborhood covid 19 jeffrey kaami mobile patrol pnco of ozamiz cps under the direct supervision of pmaj dennis pe tano offi officials ordered a lockdown thursday for 21 million people in the southwestern city of chengdu citing an insomniacsmarty oh wow the movie was on tv years ago then i remembered it when the pandemic started one common locks down 21 million people in chengdu over covid 19 outbreak times of a j christ nowplaying x lilroyce her evil spine new coronavirus cases reported in punjab newspaper all this money them niggas better capture moscow and give to us as compensation 19 update india reports 7 219 new covid 19 cases in the last 24 hours personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted pr huffpost she probably most likely got the covid 19 vax it s designed to kill murder elderly and poc persons of it is mandatory for you to wear a face mask at all times at the station or on board the train together le are still other ways to get free covid 19 tests although they may be less convenient than the white house s covid19 india covid 19 update last 24 hours new cases 7 219 recoveries 9 651 active cases 56 745 covid bonginoreport cdc panel votes in favor of recommending new covid 19 boosters that were never tested on human beings redesigned covid 19 booster shots could be available in minnesota as early as alaayous3 way officials are allowing one person in each household to go out to buy necessities once a day the person must pre s covid 19 positivity rate 7 times national average medical surgical laboratory rehabilitation equipments coronavirus preventive kits machines machine s acc tuvillanofv nowplaying x lilroyce her evil spine feat makrazy s covid 19 positivity rate 7 times national average odisha reports 174 new covid19 cases in the last 24 hours 0 18 years 13 in quarantine 102 local contacts 72 s money for everything amp everyone except the peasants it on my 5 year old to protect herself rather than modeling for her how communities protect one another that mile marker 0 cnn has mostly stayed on the right side of things although they can be cr nikkihaley nikki you mean the man who encouraged citizens to drink bleach to kill the covid 19 virus words just disgusted that money should never have been sent to prisoners give to the victims of crime of sub par wages occasional violence denial of the toilet inside the home separate utensils for domestic pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri safe stay indoor please follow guidelines issued by authorities save yourself to save others michrajah dr ananda rajah what are your thoughts as a doctor on the proposal to scrap isolation in covid19 managem robytweet sadly i wonder how often it projection it seemed like a lot of the early wave of antivax coronavirus cases in china stayed at elevated levels following the lockdown of a mega city of 21 million as th our presentation of the arctic covid 19 gender response tracker at arctic circle arctic circle assembly s me out why does it say here that people should choose mrna as 3rd boosters when people only need tw josephs26340531 i survived this long by not listening to an orange overlord ar in india live updates india reports 7 219 fresh cases and 9 651 recoveries in the last 24 fda approves the new covid 19 booster before doing human trials instead opting to judge it safe for huma should be put on unpaid leave and then quietly fired like the unvaccinated were personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re glennhamer i m not happy with biden either on this but at least i historical precedents impeded recognition of airborne covid 19 transmission bonginoreport cdc panel voters in favor of recommending covid 19 boosters that never been tested on human beings want to see your real vaccinations nobody in their right mind would get all of these murdering injections a j christ nowplaying x lilroyce tstorm05 live guyton don t get your issue your boy likes vaccines too trump s latest tweet on coronavirus might be his dumbest yet the borders have opened up human trafficking has increased how do you wash billions of dollars por 19 response plan la county department of public personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re glennhamer he s part of the labor participation problem by hyping u xe2 fda authorized updated covid 19 booster shots are effective experts say personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re just gonna be this over and over until we finally collapse in on ourselves the first redesigned covid 19 vaccine since 2020 the new bivalent boosters were developed to generate an immu covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p 19 vaccines didn work so cdc changed the definition of vaccines via the first redesigned covid 19 vaccine since 2020 the new bivalent boosters were developed to generate an immu 1 000 reports of adverse events after covid 19 vaccination in toddlers babies covid 19 test has been stopped by south korea for inbound travellers covid19 to coronavirus indian people are worst sufferer since 22 03 2020 crores of people affected lakhs of people di yorlyx s weekly covid 19 cases 27 august 1 september 2022 trudeaufortreason duped crimesagainsthumanity covid19ab covidisnotover abpoli ableg cndpoli yeg ycc case wasn aware for newly authorized covid 19 boosters based on mice not humans via the church then audit the hell out of them failed gop candidate says god will end covid 19 if u s condemns hold out the longest got an appt for sunday bivalentbooster oregon freeman and matt hancock argued at first covid 19 cobra the national have the right to refuse unsafe work but do not have the right to determine what is considered unsafe good l kuyashii desu whyyyy but haru yo koi that program saved me during my lonely nights working at covid 19 facility 219 infections india s covid 19 tally of cases to 44 49 726 death toll climbs to 27 965 govt have injected 70m of our people of sub par wages occasional violence denial of the toilet inside the home separate utensils for domestic lie friska adv eliz dara0 abidin l1e adv gateway lease waived rent waived rent reduced financial relief due to covid 19 sign the petition covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p wonder what irving city council member al zapanta is doing about covid 19 in their district company profits are collapsing like its 2020 again news social impact the perfect enemy reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily positivity r xf0 for more details visit india india profawpeet does the fact and its affiliates get over 10 000 000 in funding yearly from the nih make you l promotes sex heavy heavy heavy like most women in the industry but she never really says nothing for you to l this blog from dra pat testing keep your staff homes safe from coronavirus if they working from home suemidd58863059 really not hard start your reading here there are now new booster appointments available at cvs and walgreens just scheduled mine at the first avail suspends chinese airline flights in covid 19 19 vaccine effectiveness plunges against omicron cdc data via you believe this two elderly men theirselves saying the elderly should voluntarily die to save the economy nile virus 2nd human case this year found in massachusetts t co rrjxht8t4g xf0 denmark royal house released a brief schedule celebrating queen margrethe ii goldenjubilee which was postp am sure they won stop u from wearing a mask if u choose to wear one trudeaufortreason duped crimesagainsthumanity covid19ab covidisnotover abpoli ableg cndpoli yeg ycc xe2 the alarm bells are ringing for jobseeker so why is there now room in the budget covid19 india reports 7 219 fresh cases in last 24 hours active cases reduce to 56 745 coronavirusupdates who coronavirus disease covid 19 dashboard with vaccination data 2 september 2022 there have been 515 30 covid 19 is real mockingbird msm singing from same hymn sheet effective brainwashing used with covid19 and vaccine expectancy drops in america due to covid 19 courtesy of david flickr cc0 in 2021 the life expectancy dropped requirements south korea travel advice irs is not randomly giving away 782 as covid 19 disaster relief clicking on the link in the email will lead hello all greetings from the breadbasket states we are alive and well without masks here um serious quest covid19 now by going to your local and eating a handful of little powerful hot peppers they wil vanessa10009 the lancet covid 19 commission is headed by jeffrey sachs a person with no domain expertise in any r can we have a report on covid19 handling in india for 2021 please you get a new covid 19 booster if so when android app reviews iot flutter javascript serverless cybersecurity seosmmworld 19 gave new urgency to the science of restoring has evolved to make you sicker quicker new study finds marshablackburn biden inherited a total mess from trump who just lost his job because of his gross negligence in orla9000 the massive levels of government spending that congress threw at the pandemic including vax camps to be held on all sundays in september tn health minister source the new indian express vaxcamp stuyvesantanna yeah the study that cites the covid19 vaccine works against relaxbdg nowplaying x lilroyce her evil spine feat makrazy google maps reviews datascience python ai 100daysofcode iot truck group is hiring in elmhurst for a hr benefits administrator click now to apply rpbreakingnews new covid 19 boosters that target today most common omicron strains are set to begin soon i am fr latest the vaccines worldcourts science daily thanks to schofield covid19 science covid 19 outcomes increase in latest manitoba report cbc news xf0 denmark royal house released a brief schedule celebrating queen margrethe ii goldenjubilee which was postp governors gave lucrative no bid covid 19 deals to utah firms who then gave 1m to gop campaigns if people want to see the end of mask wearing then we need to replace masks with other public health measures that updates unionhealthministry coronavirus patientsundertreatment deathofpatients covid19 infectionrate the 51 deaths in august are more than the june and july fatalities doctors say most of these cases are among lead stories in major taiwan dailies on saturday covid19 vaccine local government elections stock picks covid19 india reports 7 219 fresh cases in last 24 hours active cases reduce to 56 745 coronavirusupdates wyonaf we have a friend whose maga husband was an ardent trump er an antimask amp antivax er he was lucky an 19 jammu and kashmir reports 152 new cases of the new cases 40 were reported from jammu and 112 from kashmi right now wakeuplagos w 176 days to nigeria s general election whose camp currently h demands rs 1 000 crore from covid19 vaccine makers for daughter s death bombay hc issues notice to sii bill authorizes updated covid 19 boosters despite lack of clinical data via t co tnexyq4klr the fda and cdc have approved new bivalent vaccines by pfizer and moderna that target both tppatriots cdc panel votes in favor of recommendi

In [ ]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
processed_docs = preprocess(complete_text)

In [ ]:
dictionary = gensim.corpora.Dictionary([processed_docs])

In [ ]:
count = 0
for k, v in dictionary.iteritems():
    print(k, v)
    count += 1
    if count > 10:
        break

0 aaaaaaaaa
1 aajtak
2 aapi
3 aapl
4 aarogya
5 aaron
6 aarondodd
7 aaronla
8 aaronparna
9 aarospeir
10 aayeff

In [ ]:
#dictionary.filter_extremes(no_below=20, no_above=0.1, keep_n= 1000000)
#dictionary.filter_extremes(no_above=0.70)

In [ ]:
dictionary

In [ ]:
#bow_corpus = dictionary.doc2bow(processed_docs)

bow_corpus = [dictionary.doc2bow(processed_docs),]
#bow_corpus = [dictionary.doc2bow(text) for text in processed_docs]
print(bow_corpus[:1])

[[]]

In [ ]:
#LDA
lda_model = gensim.models.ldamodel.LdaModel(corpus=bow_corpus, 
                                            num_topics = 20, 
                                            id2word = dictionary,
                                            random_state=100,
                                            update_every=1,
                                            chunksize=100,
                                            alpha='auto',
                                            per_word_topics=True,
                                            passes = 50)

In [ ]:
for idx, topic in lda_model.print_topics(-1):
    print("Topic: {} \nWords: {}".format(idx, topic ))
    print("\n")

In [ ]:
import re
import numpy as np
import pandas as  pd
from pprint import pprint# Gensim
import gensim
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
#from gensim.models import CoherenceModel# spaCy for preprocessing
import spacy# Plotting tools
#import pyLDAvis
#import pyLDAvis.gensim
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
!pip3 install spacy

!python3 -m spacy download en #Language model

#pip3 install gensim # For topic modeling

#pip3 install pyLDAvis # For visualizing topic models

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacy in /usr/local/lib/python3.7/dist-packages (3.4.1)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (8.1.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.64.1)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.4.4)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy) (57.4.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.9.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.23.0)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.21.6)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.10.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.7)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.8)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.6.2)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.4.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.1.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (21.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.11.3)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.6)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy) (5.2.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.6.15)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.8)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy) (2.0.1)
2022-10-06 08:48:23.784403: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
⚠ As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the
full pipeline package name 'en_core_web_sm' instead.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting en-core-web-sm==3.4.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 2.8 MB/s
Requirement already satisfied: spacy<3.5.0,>=3.4.0 in /usr/local/lib/python3.7/dist-packages (from en-core-web-sm==3.4.0) (3.4.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.4.4)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.3.0)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (8.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (21.3)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.0.8)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.21.6)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.10.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.10)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (57.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.6)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.8)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.6.2)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.4.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.9.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.23.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (4.64.1)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.11.3)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (4.1.1)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.0.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (5.2.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.24.3)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.7.8)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.1)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [ ]:
# NLTK Stop words
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
stop_words.extend(['from', 'subject', 're', 'edu', 'use'])

In [ ]:
def sent_to_words(sentences):
  for sentence in sentences:
    yield(gensim.utils.simple_preprocess(str(sentence), deacc=True))            #deacc=True removes punctuations

In [ ]:
data_words = list(sent_to_words(data))
print(data_words[:1])

[['police', 'and', 'firefighters', 'sue', 'governor', 'over', 'covid', 'vaccine', 'mandate']]

In [ ]:
bigram = gensim.models.Phrases(data_words, min_count=5, threshold=100) # higher threshold fewer phrases.
trigram = gensim.models.Phrases(bigram[data_words], threshold=100)
bigram_mod = gensim.models.phrases.Phraser(bigram)
trigram_mod = gensim.models.phrases.Phraser(trigram)
print(trigram_mod[bigram_mod[data_words[0]]])

/usr/local/lib/python3.7/dist-packages/gensim/models/phrases.py:598: UserWarning: For a faster implementation, use the gensim.models.phrases.Phraser class
  warnings.warn("For a faster implementation, use the gensim.models.phrases.Phraser class")

['police', 'and', 'firefighters_sue_governor', 'over', 'covid', 'vaccine', 'mandate']

In [ ]:
def remove_stopwords(texts):
    return [[word for word in simple_preprocess(str(doc)) if word not in stop_words] for doc in texts]

def make_bigrams(texts):
    return [bigram_mod[doc] for doc in texts]

def make_trigrams(texts):
    return [trigram_mod[bigram_mod[doc]] for doc in texts]

def lemmatization(texts, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV']):
    """https://spacy.io/api/annotation"""
    texts_out = []
    for sent in texts:
        doc = nlp(" ".join(sent)) 
        texts_out.append([token.lemma_ for token in doc if token.pos_ in allowed_postags])
    return texts_out

In [ ]:
data_words_nostops = remove_stopwords(data_words)

data_words_bigrams = make_bigrams(data_words_nostops)

nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

data_lemmatized = lemmatization(data_words_bigrams, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV'])

In [ ]:
print(data_lemmatized[:5])

[['police', 'firefighters_sue', 'governor', 'mandate'], ['new', 'case', 'report', 'record', 'covid', 'positive', 'case'], ['sm', 'supermall', 'easy', 'step'], ['hear', 'man', 'get'], ['report', 'new', 'case', 'last_hour']]

In [ ]:
id2word = corpora.Dictionary(data_lemmatized)  
texts = data_lemmatized  
corpus = [id2word.doc2bow(text) for text in texts]  
print(corpus[:1])

[[(0, 1), (1, 1), (2, 1), (3, 1)]]

In [ ]:
lda_model = gensim.models.ldamodel.LdaModel(corpus=corpus,
                                           id2word=id2word,
                                           num_topics=20, 
                                           random_state=100,
                                           update_every=1,
                                           chunksize=100,
                                           passes=50,
                                           alpha='auto',
                                           per_word_topics=True)

In [ ]:
from pprint import pprint
pprint(lda_model.print_topics())

[(0,
  '0.096*"vaccinate" + 0.061*"think" + 0.036*"last" + 0.031*"treatment" + '
  '0.030*"let" + 0.028*"member" + 0.026*"pfizer" + 0.026*"healthy" + '
  '0.024*"next" + 0.023*"month"'),
 (1,
  '0.077*"pandemic" + 0.043*"help" + 0.041*"call" + 0.036*"drug" + '
  '0.028*"concern" + 0.028*"put" + 0.025*"ivermectin_multifacete" + '
  '0.023*"keep" + 0.019*"student" + 0.018*"online"'),
 (2,
  '0.072*"tell" + 0.053*"due" + 0.051*"use" + 0.049*"school" + 0.036*"start" + '
  '0.024*"public" + 0.023*"much" + 0.019*"ever" + 0.018*"post" + '
  '0.016*"available"'),
 (3,
  '0.078*"slots_age" + 0.074*"ages_date" + 0.074*"sep_fee" + 0.060*"time" + '
  '0.043*"hospital" + 0.028*"home" + 0.028*"covaxin_dose" + 0.027*"talk" + '
  '0.018*"delta_variant" + 0.015*"sound"'),
 (4,
  '0.281*"vaccine" + 0.051*"well" + 0.050*"mandatory" + 0.042*"give" + '
  '0.041*"world" + 0.028*"show" + 0.013*"fda_approval" + 0.012*"trend" + '
  '0.011*"severe" + 0.011*"prevent"'),
 (5,
  '0.177*"people" + 0.074*"go" + 0.044*"many" + 0.041*"virus" + 0.030*"really" '
  '+ 0.024*"way" + 0.024*"family" + 0.021*"long" + 0.017*"confirm" + '
  '0.016*"mandate"'),
 (6,
  '0.187*"get" + 0.073*"test" + 0.060*"still" + 0.045*"control" + '
  '0.043*"positive" + 0.026*"big" + 0.024*"area" + 0.019*"simple" + '
  '0.017*"crisis" + 0.014*"watch"'),
 (7,
  '0.044*"good" + 0.044*"wearing_mask" + 0.040*"live" + 0.040*"country" + '
  '0.040*"life" + 0.037*"care" + 0.036*"protect" + 0.020*"other" + '
  '0.019*"line" + 0.017*"leader"'),
 (8,
  '0.101*"amp" + 0.061*"make" + 0.055*"see" + 0.042*"outbreak" + 0.026*"thank" '
  '+ 0.023*"back" + 0.021*"follow" + 0.021*"end" + 0.018*"age" + 0.013*"open"'),
 (9,
  '0.038*"know" + 0.037*"need" + 0.031*"year" + 0.026*"kid" + 0.025*"risk" + '
  '0.024*"patient" + 0.022*"today" + 0.019*"number" + 0.019*"spread" + '
  '0.019*"want"'),
 (10,
  '0.100*"health" + 0.045*"come" + 0.031*"lockdown" + 0.028*"low" + '
  '0.027*"right" + 0.024*"support" + 0.024*"level" + 0.019*"great" + '
  '0.016*"passport" + 0.015*"mass"'),
 (11,
  '0.079*"update" + 0.052*"record" + 0.040*"dose" + 0.036*"infection" + '
  '0.026*"look" + 0.024*"bad" + 0.018*"provide" + 0.016*"administer" + '
  '0.016*"second" + 0.016*"republican"'),
 (12,
  '0.056*"late" + 0.038*"travel" + 0.025*"continue" + 0.024*"business" + '
  '0.022*"boy" + 0.018*"rent" + 0.018*"rule" + 0.017*"s" + '
  '0.016*"ravi_shastri" + 0.016*"true"'),
 (13,
  '0.110*"state" + 0.028*"allow" + 0.020*"recent" + 0.019*"cause" + '
  '0.017*"ask" + 0.017*"video" + 0.015*"future" + 0.015*"essential" + '
  '0.014*"political" + 0.014*"actually"'),
 (14,
  '0.483*"covid" + 0.122*"case" + 0.079*"new" + 0.039*"report" + 0.013*"total" '
  '+ 0.012*"first" + 0.011*"recovery" + 0.009*"last_hour" + '
  '0.009*"nobel_prize" + 0.007*"face"'),
 (15,
  '0.167*"death" + 0.091*"die" + 0.056*"work" + 0.055*"news" + 0.041*"child" + '
  '0.040*"surge" + 0.040*"week" + 0.027*"datum" + 0.025*"mask" + '
  '0.019*"force"'),
 (16,
  '0.092*"day" + 0.046*"county" + 0.031*"even" + 0.026*"booster_shot" + '
  '0.023*"require" + 0.022*"unvaccinated" + 0.022*"ban" + 0.020*"huge" + '
  '0.018*"close" + 0.018*"full"'),
 (17,
  '0.085*"take" + 0.051*"government" + 0.041*"high" + 0.029*"hospitalize" + '
  '0.026*"treat" + 0.022*"lie" + 0.019*"lose" + 0.017*"hit" + 0.017*"medium" + '
  '0.016*"fully_vaccinate"'),
 (18,
  '0.154*"say" + 0.133*"vaccination" + 0.034*"find" + 0.031*"also" + '
  '0.027*"doctor" + 0.026*"study" + 0.020*"link" + 0.020*"testing" + '
  '0.019*"daily" + 0.018*"story"'),
 (19,
  '0.082*"coronavirus" + 0.040*"insight" + 0.031*"increase" + 0.030*"variant" '
  '+ 0.029*"active" + 0.024*"feel" + 0.024*"hear" + 0.023*"young" + '
  '0.019*"impact" + 0.019*"expert"')]

In [ ]:
for idx, topic in lda_model.show_topics(formatted=False, num_topics=20, num_words= 100):
    print('Topic: {} \nWords: {}'.format(idx, '|'.join([w[0] for w in topic])))

Topic: 0
Words: vaccinate|think|last|treatment|let|member|pfizer|healthy|next|month|infect|manage|away|hope|less|group|sign|result|smartnew|apparently|stay|immunity|qualifi|centre|imagine|suppose|fully|wcepi|cure|petition|covidiot|whole|speak|past|year_old|contract|percent|transmit|damage|tourist|concerned|notice|attack|holocaust|immediately|biden|come_later|natural|scary|antibody|similar|recognize|island|embrace|veteran|dose_regiman|ability|liberal|airline|woman_die|amount|trade|file|oppose|candidate|diagnosis|brain_disease|suddenly|firm|special|insider|sister|deltavariant|gold|twice|favorite|generate|achieve_herd|japanese|lagos_consider|drunk|section|goal|world_cup|visa|bet|drink|sebgorka|kidney|seven_minute|movie|speedy_recovery|hit_peak|snake|exam|epidemiology|running_ex|foundation|randomized_controlle|niece
Topic: 1
Words: pandemic|help|call|drug|concern|put|ivermectin_multifacete|keep|student|online|rise|indicated_efficacy|check|least|understand|horrible|fight|chat|visit|friend|drive|almost|order|misinformation|send|yet|measure|part|detail|lack|sends_tonne|vote|scientist|choose|volunteer|fine|baby|stadium|massive|vaxxe|getvaccinate|answer|director|search|voice|pack|highly|commit|save|death_toll|rapid|screw|criminal|combat|postponed_due|opinion|fatality|protection|excess|request|pace|phase|suppress|carry|water|liver|proud_boy|regard|president|africanunion|seasonal|alternative|liar|illness|shortage|resignation|faces_deadli|aim|mumbai|tv|understanding|suicide|review|taxpayer|esp|own|phone|adopt|plenty|blind|thehill|usage|park|beshear|forward|loan|eradicate|pastor|enemy|engage
Topic: 2
Words: tell|due|use|school|start|public|much|ever|post|available|medical|handle|do|fall|australian|man|wrong|parent|return|expensive|amass|reopen|individual|nurse|industry|money|sad|token|strategy|staff_member|term|person_learne|limit|scientific|pretty|board|spike|overwhelm|correct|program|track|picture|meeting|amazing|green|remove|opening|initiative|beat|certain|tomorrow|chain|assistance|proceed|ill|surpass|donor|pilot|mark|division|requirement|retain|honor|extra|assessment|graph|specialist|gathering|implementation|locate|compliance|researcher|corona|scene|surprise|university|shame|enjoy|weight|ruin|college|rush|particular|crazy|cm|stude|privilege|developed_countrie|overall|mail|donald_trump|overseas|brain|rarely|clarify|moral|antivaxxer|operate|french|succeed
Topic: 3
Words: slots_age|ages_date|sep_fee|time|hospital|home|covaxin_dose|talk|delta_variant|sound|co|service|politic|job|wave|receive|experience|claim|los_angele|authority|fire|govt|fatigue|sept|struggle|apollo_cli|probably|accord|fee|survey|average|employees_worke|keep_tab|sport|seriously|critical|former|date_sep|write|officer|sector|apollo_cl|waste|common|secretary|traveller|status|conservative|federal|side_effect|idiot|field|danger|clash|delay|certainly|financial|illegal|rage|basis|dispute|creation|injection|absolutely|invite|household|jump|sympathy|central|channel|swamp|address|email|difficult|temporary|ravage|teen|capacity|tha|federal_legalization|marijuana_practically|press|north|device|elect|pr|regulation|painless|gene|hotel|chunk|adoption|tr|hard_heade|urges_fellow|practice|poem_potential|side|brush|eviction
Topic: 4
Words: vaccine|well|mandatory|give|world|show|fda_approval|trend|severe|prevent|research|buy|join|different|cost|arrive|step|able|access|gain|breach|deal|fear|indicate|propose|damn|fauci_stresse|project|observe|book|delta|pre|avenger|efficacy|incentive|judge_order|house_spat|compare|hero_support|technology|interrupt|process|distract|capital|mostly|lawsuit|prime_wardrobe|feet_men|key|proud|roughly|introduce|software|immune|chinese|behavior|nd_dose|viruse|outcome|natural_immunity|poll|adverse_event|exemption|believes_delivery|women|years_ago|polio|principle|clown|switch|hesitate|hike|life_save|rich_countrie|related|shoes_stayhome|land|dollar|shoe|computer|daughter|childre|oil|pregnant_woman|tech|questions_answere|expire|myth|consumer|coronav|replacement|cbc_radio|top_infectious|wane|debate|bit_distracte|protection_vanishe|asean|moratorium|warning
Topic: 5
Words: people|go|many|virus|really|way|family|long|confirm|mandate|staff|kill|recover|believe|govabbott|third|hub|symptom|learn|release|jab|loss|deadly|dam|consider|comment|push|wake|major|mom|account|majority|police|appear|antibodie|thousand|extend|sorry|download|witness|governor|smell|incredible|statement|token|quick|insanity|everywhere|social_media|vs|violate|super_spreader|economic|arrest|strand|thin|unmasked|stick|planning|easily|adverse|prioritize|sometimes|dozen|sit|deer|fool|vacci|could_affect|breath|recall|fro|disgrace|bout|re|significantly|planet|advantage|avenger|slide|naturally|hunters_need|bill|hero_support|triage|diversity|lean|universal|stretch|di|submit|deserve|anywhere|epidemiological|reporter|collect|realise|gunshot_victim|lo|brilliant
Topic: 6
Words: get|test|still|control|positive|big|area|simple|crisis|watch|focus|old|weekend|always|wonder|message|guy|fast|explain|season|negative|bit|single|hero_support|lab|avenger|xe|token|double|obvious|schedule|regional|vaxxed|availability|completely|player|perhaps|wish|hurt|fan|resist_resister|round|distribute|reportedly|welcome|recommend|pray|well_soon|somewhere|surprised|shift|dem|thinking|zack_martin|manufacturer|par|destroy|rip|profit_nearly|lockdowns_ease|truly|fbrparty_resister|conference|law|store|kit|ward|vaxe|entertainment|rathour|fbr|sho|surgery|ingredient|trouble|lol|sponsor|sin|app|cricket|convenient|pcr_t|shastri_test|dropping|pcr|wound|meaning|tremendous|catholic|antigen|wellbee|swab|cowboy|keeper_steffen|renew|funny|dumb_fuqs|making|malay_mail|bee
Topic: 7
Words: good|wearing_mask|live|country|life|care|protect|other|line|leader|change|dead|real|sick|urge|shot|reason|stupid|nz|bed|fail|military|spend|animal|avoid|blame|hard|freedom|pass|hero_support|ventilator|dangerous|lift|avenger|center|de|eat|mild|standard|badly|tough|scream|conduct|insurance|wil|material|accept|dude|chapter|manufacture|aboriginal|indeed|senator|med|forever|democracy|travel_ban|build|employer|draw|dad|delivery|labour|advice|xf|project_topic|complete_project|ve|code|closure|commissioner_fighte|complex|grief|moderate|hero|threat|method|monroe_county|excuse|evil|ignorant|injury|express|novel|eve|md|inquiry|prosecute|assumption|msm|document|customer|worm|inch|pure|seymour|unit|enable|career|shameful
Topic: 8
Words: amp|make|see|outbreak|thank|back|follow|end|age|open|coverage|healthcare_worker|fuck|reach|decision|science|act|move|stress|refuse|border|anti|else|suspend|auspol|attend|worth|fund|register|date|weekly|climate|star|washington_post|cut|social|narrative|hero_support|budget|extremely|avenger|preach|chart|disinformation|party|climate_change|disability|present|reality|pro|agency|province|percentage|surge_pose|experimental|hospital_admission|milestone|stat|selfish|pick|angry|partner|religious|serve|certificate|dumb|facility|skill|disgusting|select|wheel|surveillance|trauma|text|onset|value|anyway|ptsd|profit|christian|circumstance|useless|regime|propaganda|moderna|pressure|violation|voter|upset|super|beneficiarie|accurate|pediatric|around|front_line|maga|bill_gate|champion|organisation|alert
Topic: 9
Words: know|need|year|kid|risk|patient|today|number|spread|want|stop|never|happen|try|safe|read|community|thing|person|booster|mean|include|agree|base|heart|play|tool|global|relief|situation|already|free|place|potential|worker|point|source|reduce|sweden|relate|become|vitamin|expect|fact|game|wait|list|economy|trump|leave|body|row|course|peak|shut|bring|grow|lock|host|half|mention|oxygen|food|football|lot|ignore|choice|office|power|seek|literally|note|resident|possible|doubt|nearly|minister|site|court|loved_one|remember|interview|especially|forget|nice|students_quarantine|infectious|earn|radio|avenger|protester|hell|handling|thought|supply|clear|celebrate|cancel|proper|plea
Topic: 10
Words: health|come|lockdown|low|right|support|level|great|passport|mass|team|freight|restriction|sure|issue|company|soon|top|obviously|effect|figure|encourage|publish|shit|apply|admit|pro_life|model|approve|icu_bed|morning|blood|guideline|appointment|officials_storm|save_live|digital|stuff|flag|ready|frontline|light|listen|entry|matter|raise|payment|definitely|expand|election|pitch|movement|improve|melbourne|administration|soft|wh|idea|aware|attempt|homelessness|brazilian|decrease|clearly|bar|attention|generally|net|slightly|achieve|contact_trace|peo|pub|large_venue|sharp|municipal|shop|sleep|direct|posit|feature|cancer|idaho|ch|vial|honestly|mi|decade|wide|migrant|era|mulls_introduction|sunil_perera|await|agenda|rely|penny|dedicated|ky|elderly
Topic: 11
Words: update|record|dose|infection|look|bad|provide|administer|second|republican|sh|pm|article|current|safety|mini|latter_fire|firefight_erupte|information|announce|info|sri_lanka|suggest|strain|page|astrazeneca|modelling|thread|nsw|prevention|entire|evidence|website|market|memorial|twitter|type|policy|night|interest|cluster|covi|seven_stage|boost|discussion|trial|parasite|connect|poor|nyt|resource|declare|live_update|viral|location|topic|senior|session|mortality|car|respond|prior|rental|treatment_option|apple|hospitalise|disappointed_doctor|ed|weather|dewormer|product|pune|study_find|tracking|again|scenario|near|rollingstone|exposure_site|suspension|music|antibody_stop|particularly|seat|paper|traffic|throw|highest|labor|opener|size|experiment|perfect|blast|shortly|automation|sake|receipt|marvel|finger
Topic: 12
Words: late|travel|continue|business|boy|rent|rule|s|ravi_shastri|true|official|love|airport|human|prove|view|roll|education|exist|truth|serious|additional|identify|enter|folk|diagnose|realize|sc|failure|daily_thank|small|m|cell|shock|strong|stay_safe|taste|management|medicine|church|prescribe|fly|however|charge|hoax|allege|stage|promote|isolate|totally|international|prime_minister|keeping_hawai|travel_guideline|genetic|rest|cov|transit|peace|development|ridiculous|produce|severity|option|slam|legal|town|generation|match_abandone|contribution|vaccin|importance|network|uncertainty|modi|dear|insane|headache|caution|veterinarian|quality|afflict|con|repeat|ailment|draft|assess|scientific_advisor|pl|european|swath|perform|letter|third_wave|emergence|machine|permanently|enhypen|living|conspiracist_die
Topic: 13
Words: state|allow|recent|cause|ask|video|future|essential|political|actually|employee|nytpolitic|effective|fake|class|th|million|emergency|word|city|head|little|sense|maybe|several|district|leadership|hand|shoulder|shoot|wear|american|worry|air|launch|contagious|gather|isolation|anti_vaxxer|card|abandon|simply|department|anchor|premier|aid|society|effort|like|crossroad|represents_perilous|rural|chief|discover|victim|challenge|states_ut|survive|jail|general|ass|rd|false|enzyme|invent|yo|quite|hide|priority|british|te|possibly|labor_day|owner|silent|subscriber|thi|war|later|triple|bu|popular|maharashtra|conversation|chaos|provider|sue|photo|absolute|affair|error|tap|mil|operation|native|unemployment_benefit|zone|guarantee|balance|deeply
Topic: 14
Words: covid|case|new|report|total|first|recovery|last_hour|nobel_prize|face|rate|grant|response|honoured_distinction|break|inadequate|disease|protocol|detect|action|problem|currently|important|count|map|reuter|region|instead|stand|slow|south_wale|interact|controversy|breakthrough|campaign|epidemic|week_period|finally|pop|approach|log|gun|significant|previous|race|sar|click|auckland|norm|consecutive|locally_acquire|statistic|com|tally|dip|vaccinated|limited|positivity_rate|combine|rat|hospitalization|updates_globally|updated_septe|slight|celebration|wa|occur|pos|pollution|hot|avenger|york_time|nepal|hero_support|global_sc|pradesh|narendra_modi|criticize|said_nigerian|outstanding|skyrocket|hit_peak|qualifier|tamilnadu|numbe|visualizations_give|token|poem_potential|positivity|rogue|vic|valley|surface|kitchen|cleaning|globally|ritapanahi|beneficiarie|six_month|global_economie
Topic: 15
Words: death|die|work|news|child|surge|week|datum|mask|force|far|drop|rally|flu|add|condition|worldwide|share|suffer|minute|remain|easy|western|ago|alone|fda_expert|represent|investigate|recently|complication|mind|expose|predict|couple|foxnew|inequality|past_hour|gt|others_injure|analysis|husband|bear|fox|regularly|tip|vaccinat|though|hospitalisation|hire|contracting|debt|hearing|sentence|caseload|harm|gregabbott_tx|sacrifice|social_distance|lung|consequence|plague|surely|afternoon|pneumonia|preventable|fetus|vulnerable|recovered_active|hospitals_crushe|dire|distance|mid|exact|subscriber|hit_peak|stroke|divide|avenger|cough|tyranny|inmate|hero_support|birthday|diagnostic|ignorance|indian|sharing|ethical|rampage|figures_show|fence|impressive|prevent_winter|obese|gre|eligible|rogan_reveal|mhra|spontanous_abortion|false_claim
Topic: 16
Words: day|county|even|booster_shot|require|unvaccinated|ban|huge|close|full|exposure|quarantine|early|beca|teacher|set|pay|reveal|catch|enough|approval|fauci_stresse|nation|house_spat|tackle|cover|miss|battle|normal|national|implement|summer|complete|restaurant|solution|fill|straight|together|protest|participant|ease|happy|decide|abortion|austin|judge|tablet|organize|pill|price|aged|tax|deep|brief|moron|dog|philippine|respect|utter|discipline|adolescent|crime|award|conclusion|holiday|self|village|success|doctors_nurse|adviser|quit|bigger_factor|patients_stream|accustom|afford|mississippi_hospital|hotspot|soar|spot|strict|personality|impossible|beg|urgent|meet|argentina|adapt|smoking|food_gadget|exclusive|legally|brother|hong_kong|arrival|compulsory|learning|podcast|transport|hating|conservative_media
Topic: 17
Words: take|government|high|hospitalize|treat|lie|lose|hit|medium|fully_vaccinate|likely|affect|ivermectin|lead|question|woman|train|event|tweet|united_state|develop|mirror|transmission|demand|opportunity|mother|responsible|walk|growth|associate|clinical_trial|fix|application|endemic|history|crowd|icu|contain|ppl|remind|quote|toll|chance|short|allegedly|unproven|exactly|cash|front|healthcare|vacc|fair|authorize|data|position|example|precaution|incidence|none|college_student|funeral|chip|chunk|finding|credit|festival|necessary|glad|demonstrate|youth|odd|factor|giant|breathe|climb|highlight|fucking|incident|advise|tonight|mask_wishe|died_screaming|reminder|final|unvaccinate|rich|asymptomatic|person_classe|weird|biology|politician|vaccina|human_right|resolve|defeat|asian|mo|plasma|covaxin|napa
Topic: 18
Words: say|vaccination|find|also|doctor|study|link|testing|daily|story|plan|local|offer|large|hold|run|rollout|newsbreak|system|begin|create|las_vega|target|zealand_report|proof|interesting|covidvaccine|flight|accuse|bullshit|deny|obesity|prepare|hero_support|rather|quickly|income|plane|avenger|estimate|exceed|discuss|refer|clinical|humanity|portion|reject|parade|briefing|brady_confirm|cr|film|south_korea|image|tourism|nervous_system|buccaneers_super|workplace|various|candace_owen|assume|resort|series|fourth|definition|parliamentary|few|minor|initial|ramp|arkansas_jail|secure|promise|mouth|main|production|cumulative|unlikely|red|confuse|ivermectin_overdose|contribution_count|terrible|effects_linke|center_denie|outpatient|multiple_sclerosis|argue|committee|queensland|severe_illness|bacteria|typical|demyelination|fifth|toe|irresponsible|extensive|woe|pharmacy
Topic: 19
Words: coronavirus|insight|increase|variant|active|feel|hear|young|impact|expert|turn|warn|population|seem|yesterday|clinic|actual|resistance|black|fauci|guess|origin|rampage|florida_summ|fresh|piece|adult|hour|sample|name|ahead|citizen|guardian|girl|one|warm|activity|kind|contribute|latinos_remain|racist|tested_positive|mu_variant|smart|form|physical|moment|decimate|trace|sell|dictatorship|cold|resistant|pattern|import|strongly|deputy|gap|strange|determine|professor|table|restrict|wild|cat|establish|mine|ship|nonsense|originate|infect_volunteer|ceo|pe|design|garbage|index|origins_trace|appreciate|numb|officially|nytpolitic|politicize|broadcast|previously|sequence|emerge|rehabilitation|headline|reward|servant|finance|white|lag|constantly|surprising|specific|gust_kmh|rain_since|avg_wind|constituent

In [ ]:
from gensim.parsing.preprocessing import preprocess_string, strip_punctuation, strip_numeric

lda_topics = lda_model.show_topics(num_topics=20, num_words=50)

topics = []
filters = [lambda x: x.lower(), strip_punctuation, strip_numeric]

for topic in lda_topics:
    print(topic)
    topics.append(preprocess_string(topic[1], filters))

print(topics)

(0, '0.096*"vaccinate" + 0.061*"think" + 0.036*"last" + 0.031*"treatment" + 0.030*"let" + 0.028*"member" + 0.026*"pfizer" + 0.026*"healthy" + 0.024*"next" + 0.023*"month" + 0.020*"infect" + 0.019*"manage" + 0.018*"away" + 0.015*"hope" + 0.012*"less" + 0.012*"group" + 0.011*"sign" + 0.011*"result" + 0.011*"smartnew" + 0.011*"apparently" + 0.010*"stay" + 0.010*"immunity" + 0.009*"qualifi" + 0.008*"centre" + 0.007*"imagine" + 0.007*"suppose" + 0.007*"fully" + 0.007*"wcepi" + 0.006*"cure" + 0.006*"petition" + 0.006*"covidiot" + 0.006*"whole" + 0.005*"speak" + 0.005*"past" + 0.005*"year_old" + 0.005*"contract" + 0.005*"percent" + 0.004*"transmit" + 0.004*"damage" + 0.004*"tourist" + 0.004*"concerned" + 0.004*"notice" + 0.004*"attack" + 0.003*"holocaust" + 0.003*"immediately" + 0.003*"biden" + 0.003*"come_later" + 0.003*"natural" + 0.003*"scary" + 0.003*"antibody"')
(1, '0.077*"pandemic" + 0.043*"help" + 0.041*"call" + 0.036*"drug" + 0.028*"concern" + 0.028*"put" + 0.025*"ivermectin_multifacete" + 0.023*"keep" + 0.019*"student" + 0.018*"online" + 0.017*"rise" + 0.016*"indicated_efficacy" + 0.015*"check" + 0.015*"least" + 0.014*"understand" + 0.013*"horrible" + 0.013*"fight" + 0.012*"chat" + 0.012*"visit" + 0.011*"friend" + 0.010*"drive" + 0.009*"almost" + 0.009*"order" + 0.009*"misinformation" + 0.009*"send" + 0.008*"yet" + 0.008*"measure" + 0.008*"part" + 0.008*"detail" + 0.007*"lack" + 0.007*"sends_tonne" + 0.007*"vote" + 0.007*"scientist" + 0.007*"choose" + 0.006*"volunteer" + 0.006*"fine" + 0.006*"baby" + 0.006*"stadium" + 0.006*"massive" + 0.005*"vaxxe" + 0.005*"getvaccinate" + 0.005*"answer" + 0.005*"director" + 0.004*"search" + 0.004*"voice" + 0.004*"pack" + 0.004*"highly" + 0.004*"commit" + 0.004*"save" + 0.004*"death_toll"')
(2, '0.072*"tell" + 0.053*"due" + 0.051*"use" + 0.049*"school" + 0.036*"start" + 0.024*"public" + 0.023*"much" + 0.019*"ever" + 0.018*"post" + 0.016*"available" + 0.015*"medical" + 0.015*"handle" + 0.011*"do" + 0.011*"fall" + 0.011*"australian" + 0.010*"man" + 0.010*"wrong" + 0.009*"parent" + 0.009*"return" + 0.008*"expensive" + 0.007*"amass" + 0.007*"reopen" + 0.007*"individual" + 0.007*"nurse" + 0.006*"industry" + 0.006*"money" + 0.006*"sad" + 0.006*"token" + 0.006*"strategy" + 0.005*"staff_member" + 0.005*"term" + 0.005*"person_learne" + 0.005*"limit" + 0.005*"scientific" + 0.004*"pretty" + 0.004*"board" + 0.004*"spike" + 0.004*"overwhelm" + 0.004*"correct" + 0.004*"program" + 0.004*"track" + 0.003*"picture" + 0.003*"meeting" + 0.003*"amazing" + 0.003*"green" + 0.003*"remove" + 0.003*"opening" + 0.003*"initiative" + 0.003*"beat" + 0.003*"certain"')
(3, '0.078*"slots_age" + 0.074*"sep_fee" + 0.074*"ages_date" + 0.060*"time" + 0.043*"hospital" + 0.028*"home" + 0.028*"covaxin_dose" + 0.027*"talk" + 0.018*"delta_variant" + 0.015*"sound" + 0.015*"co" + 0.012*"service" + 0.012*"politic" + 0.011*"job" + 0.011*"wave" + 0.011*"receive" + 0.010*"experience" + 0.010*"claim" + 0.009*"los_angele" + 0.009*"authority" + 0.008*"fire" + 0.008*"govt" + 0.008*"fatigue" + 0.008*"sept" + 0.007*"struggle" + 0.006*"apollo_cli" + 0.006*"probably" + 0.006*"accord" + 0.005*"fee" + 0.005*"survey" + 0.005*"average" + 0.005*"keep_tab" + 0.005*"employees_worke" + 0.005*"sport" + 0.004*"seriously" + 0.004*"critical" + 0.004*"former" + 0.004*"date_sep" + 0.004*"write" + 0.004*"officer" + 0.004*"sector" + 0.004*"apollo_cl" + 0.004*"waste" + 0.004*"common" + 0.004*"secretary" + 0.004*"traveller" + 0.004*"status" + 0.003*"conservative" + 0.003*"federal" + 0.003*"side_effect"')
(4, '0.281*"vaccine" + 0.051*"well" + 0.050*"mandatory" + 0.042*"give" + 0.041*"world" + 0.028*"show" + 0.013*"fda_approval" + 0.012*"trend" + 0.011*"severe" + 0.011*"prevent" + 0.010*"research" + 0.010*"buy" + 0.008*"join" + 0.008*"different" + 0.008*"cost" + 0.008*"arrive" + 0.007*"step" + 0.007*"able" + 0.006*"access" + 0.006*"gain" + 0.006*"breach" + 0.005*"deal" + 0.005*"fear" + 0.005*"indicate" + 0.005*"propose" + 0.004*"damn" + 0.004*"fauci_stresse" + 0.004*"project" + 0.004*"observe" + 0.004*"book" + 0.004*"delta" + 0.004*"pre" + 0.003*"avenger" + 0.003*"efficacy" + 0.003*"incentive" + 0.003*"judge_order" + 0.003*"house_spat" + 0.003*"compare" + 0.003*"hero_support" + 0.003*"technology" + 0.003*"interrupt" + 0.003*"process" + 0.003*"distract" + 0.003*"capital" + 0.003*"mostly" + 0.003*"lawsuit" + 0.003*"prime_wardrobe" + 0.003*"feet_men" + 0.003*"key" + 0.002*"proud"')
(5, '0.177*"people" + 0.074*"go" + 0.044*"many" + 0.041*"virus" + 0.030*"really" + 0.024*"way" + 0.024*"family" + 0.021*"long" + 0.017*"confirm" + 0.016*"mandate" + 0.016*"staff" + 0.014*"kill" + 0.014*"recover" + 0.013*"believe" + 0.013*"govabbott" + 0.012*"third" + 0.012*"hub" + 0.011*"symptom" + 0.011*"learn" + 0.011*"release" + 0.009*"jab" + 0.009*"loss" + 0.008*"deadly" + 0.008*"dam" + 0.008*"consider" + 0.006*"comment" + 0.006*"push" + 0.006*"wake" + 0.005*"major" + 0.004*"mom" + 0.004*"account" + 0.004*"majority" + 0.004*"police" + 0.004*"appear" + 0.003*"antibodie" + 0.003*"thousand" + 0.003*"extend" + 0.003*"sorry" + 0.003*"download" + 0.003*"witness" + 0.003*"governor" + 0.003*"smell" + 0.003*"incredible" + 0.003*"statement" + 0.003*"token" + 0.003*"quick" + 0.003*"insanity" + 0.002*"everywhere" + 0.002*"social_media" + 0.002*"vs"')
(6, '0.187*"get" + 0.073*"test" + 0.060*"still" + 0.045*"control" + 0.043*"positive" + 0.026*"big" + 0.024*"area" + 0.019*"simple" + 0.017*"crisis" + 0.014*"watch" + 0.012*"focus" + 0.011*"old" + 0.010*"weekend" + 0.010*"always" + 0.010*"wonder" + 0.009*"message" + 0.008*"guy" + 0.008*"fast" + 0.008*"explain" + 0.007*"season" + 0.007*"negative" + 0.007*"bit" + 0.007*"single" + 0.006*"hero_support" + 0.006*"lab" + 0.006*"avenger" + 0.005*"xe" + 0.005*"token" + 0.005*"double" + 0.005*"obvious" + 0.005*"schedule" + 0.005*"regional" + 0.004*"vaxxed" + 0.004*"availability" + 0.004*"completely" + 0.004*"player" + 0.004*"perhaps" + 0.003*"wish" + 0.003*"hurt" + 0.003*"fan" + 0.002*"resist_resister" + 0.002*"round" + 0.002*"distribute" + 0.002*"reportedly" + 0.002*"welcome" + 0.002*"recommend" + 0.002*"pray" + 0.002*"well_soon" + 0.002*"somewhere" + 0.002*"surprised"')
(7, '0.044*"good" + 0.044*"wearing_mask" + 0.040*"live" + 0.040*"country" + 0.040*"life" + 0.037*"care" + 0.036*"protect" + 0.020*"other" + 0.019*"line" + 0.017*"leader" + 0.016*"change" + 0.015*"dead" + 0.015*"real" + 0.013*"sick" + 0.012*"urge" + 0.010*"shot" + 0.009*"reason" + 0.009*"stupid" + 0.008*"nz" + 0.008*"bed" + 0.008*"fail" + 0.007*"military" + 0.007*"spend" + 0.007*"animal" + 0.007*"avoid" + 0.007*"blame" + 0.007*"hard" + 0.007*"freedom" + 0.007*"pass" + 0.007*"hero_support" + 0.006*"ventilator" + 0.006*"dangerous" + 0.006*"lift" + 0.006*"avenger" + 0.005*"center" + 0.005*"de" + 0.005*"eat" + 0.005*"mild" + 0.004*"standard" + 0.004*"badly" + 0.004*"tough" + 0.004*"scream" + 0.004*"conduct" + 0.004*"insurance" + 0.004*"wil" + 0.004*"material" + 0.004*"accept" + 0.003*"dude" + 0.003*"chapter" + 0.003*"manufacture"')
(8, '0.101*"amp" + 0.061*"make" + 0.055*"see" + 0.042*"outbreak" + 0.026*"thank" + 0.023*"back" + 0.021*"follow" + 0.021*"end" + 0.018*"age" + 0.013*"open" + 0.013*"coverage" + 0.012*"healthcare_worker" + 0.011*"fuck" + 0.011*"reach" + 0.011*"decision" + 0.009*"science" + 0.008*"act" + 0.008*"move" + 0.008*"stress" + 0.007*"refuse" + 0.007*"border" + 0.006*"anti" + 0.006*"else" + 0.006*"suspend" + 0.006*"auspol" + 0.005*"attend" + 0.005*"worth" + 0.005*"fund" + 0.005*"register" + 0.005*"date" + 0.005*"weekly" + 0.005*"climate" + 0.005*"star" + 0.005*"washington_post" + 0.004*"cut" + 0.004*"social" + 0.004*"narrative" + 0.004*"hero_support" + 0.004*"budget" + 0.004*"extremely" + 0.004*"avenger" + 0.004*"preach" + 0.004*"chart" + 0.004*"disinformation" + 0.003*"party" + 0.003*"climate_change" + 0.003*"disability" + 0.003*"present" + 0.003*"reality" + 0.003*"pro"')
(9, '0.038*"know" + 0.037*"need" + 0.031*"year" + 0.026*"kid" + 0.025*"risk" + 0.024*"patient" + 0.022*"today" + 0.019*"number" + 0.019*"spread" + 0.019*"want" + 0.019*"stop" + 0.016*"never" + 0.014*"happen" + 0.014*"try" + 0.014*"safe" + 0.014*"read" + 0.014*"community" + 0.014*"thing" + 0.012*"person" + 0.012*"booster" + 0.011*"mean" + 0.010*"include" + 0.010*"agree" + 0.010*"base" + 0.009*"heart" + 0.009*"play" + 0.009*"tool" + 0.009*"global" + 0.008*"relief" + 0.008*"situation" + 0.008*"already" + 0.008*"free" + 0.007*"place" + 0.007*"potential" + 0.007*"worker" + 0.007*"point" + 0.007*"source" + 0.007*"reduce" + 0.007*"sweden" + 0.007*"relate" + 0.007*"become" + 0.007*"vitamin" + 0.007*"expect" + 0.006*"fact" + 0.006*"game" + 0.005*"wait" + 0.005*"list" + 0.005*"economy" + 0.005*"trump" + 0.005*"leave"')
(10, '0.100*"health" + 0.045*"come" + 0.031*"lockdown" + 0.028*"low" + 0.027*"right" + 0.024*"support" + 0.024*"level" + 0.019*"great" + 0.016*"passport" + 0.015*"mass" + 0.015*"team" + 0.013*"freight" + 0.013*"restriction" + 0.013*"sure" + 0.013*"issue" + 0.011*"company" + 0.011*"soon" + 0.010*"top" + 0.010*"obviously" + 0.009*"effect" + 0.009*"figure" + 0.008*"encourage" + 0.008*"publish" + 0.008*"shit" + 0.008*"apply" + 0.008*"admit" + 0.008*"pro_life" + 0.007*"model" + 0.007*"approve" + 0.007*"icu_bed" + 0.006*"morning" + 0.006*"blood" + 0.005*"guideline" + 0.005*"appointment" + 0.005*"officials_storm" + 0.005*"save_live" + 0.005*"digital" + 0.004*"stuff" + 0.004*"flag" + 0.004*"ready" + 0.004*"frontline" + 0.004*"light" + 0.004*"listen" + 0.004*"entry" + 0.004*"matter" + 0.004*"raise" + 0.004*"payment" + 0.004*"definitely" + 0.004*"expand" + 0.004*"election"')
(11, '0.079*"update" + 0.052*"record" + 0.040*"dose" + 0.036*"infection" + 0.026*"look" + 0.024*"bad" + 0.018*"provide" + 0.016*"administer" + 0.016*"second" + 0.016*"republican" + 0.015*"sh" + 0.014*"pm" + 0.014*"article" + 0.013*"current" + 0.012*"safety" + 0.012*"mini" + 0.011*"latter_fire" + 0.011*"firefight_erupte" + 0.011*"information" + 0.011*"announce" + 0.010*"info" + 0.010*"sri_lanka" + 0.009*"suggest" + 0.008*"strain" + 0.007*"page" + 0.006*"astrazeneca" + 0.006*"modelling" + 0.006*"thread" + 0.006*"nsw" + 0.006*"prevention" + 0.006*"entire" + 0.005*"evidence" + 0.005*"website" + 0.005*"market" + 0.005*"memorial" + 0.005*"twitter" + 0.005*"type" + 0.005*"policy" + 0.005*"night" + 0.005*"interest" + 0.005*"cluster" + 0.005*"covi" + 0.005*"seven_stage" + 0.004*"boost" + 0.004*"discussion" + 0.004*"trial" + 0.004*"parasite" + 0.004*"connect" + 0.004*"poor" + 0.004*"nyt"')
(12, '0.056*"late" + 0.038*"travel" + 0.025*"continue" + 0.024*"business" + 0.022*"boy" + 0.018*"rent" + 0.018*"rule" + 0.017*"s" + 0.016*"ravi_shastri" + 0.016*"true" + 0.015*"official" + 0.014*"love" + 0.012*"airport" + 0.012*"human" + 0.011*"prove" + 0.009*"view" + 0.009*"roll" + 0.008*"education" + 0.008*"exist" + 0.008*"truth" + 0.008*"serious" + 0.008*"additional" + 0.008*"identify" + 0.007*"enter" + 0.007*"folk" + 0.007*"diagnose" + 0.007*"realize" + 0.007*"sc" + 0.006*"failure" + 0.006*"daily_thank" + 0.006*"small" + 0.006*"m" + 0.006*"cell" + 0.006*"shock" + 0.006*"strong" + 0.006*"stay_safe" + 0.006*"taste" + 0.005*"management" + 0.005*"medicine" + 0.005*"church" + 0.005*"prescribe" + 0.005*"fly" + 0.005*"however" + 0.005*"charge" + 0.005*"hoax" + 0.005*"allege" + 0.005*"stage" + 0.005*"promote" + 0.004*"isolate" + 0.004*"totally"')
(13, '0.110*"state" + 0.028*"allow" + 0.020*"recent" + 0.019*"cause" + 0.017*"ask" + 0.017*"video" + 0.015*"future" + 0.015*"essential" + 0.014*"political" + 0.014*"actually" + 0.013*"employee" + 0.012*"nytpolitic" + 0.012*"effective" + 0.011*"fake" + 0.010*"class" + 0.010*"th" + 0.010*"million" + 0.009*"emergency" + 0.008*"word" + 0.008*"city" + 0.008*"head" + 0.008*"little" + 0.007*"sense" + 0.007*"maybe" + 0.007*"several" + 0.007*"district" + 0.007*"leadership" + 0.007*"hand" + 0.007*"shoulder" + 0.007*"shoot" + 0.007*"wear" + 0.006*"american" + 0.006*"worry" + 0.006*"air" + 0.006*"launch" + 0.006*"contagious" + 0.006*"gather" + 0.006*"isolation" + 0.006*"anti_vaxxer" + 0.006*"card" + 0.005*"abandon" + 0.005*"simply" + 0.005*"department" + 0.005*"anchor" + 0.005*"premier" + 0.005*"aid" + 0.004*"society" + 0.004*"effort" + 0.004*"like" + 0.004*"crossroad"')
(14, '0.483*"covid" + 0.122*"case" + 0.079*"new" + 0.039*"report" + 0.013*"total" + 0.012*"first" + 0.011*"recovery" + 0.009*"last_hour" + 0.009*"nobel_prize" + 0.007*"face" + 0.007*"rate" + 0.006*"grant" + 0.006*"response" + 0.006*"honoured_distinction" + 0.006*"break" + 0.005*"inadequate" + 0.004*"disease" + 0.004*"protocol" + 0.004*"detect" + 0.004*"action" + 0.004*"problem" + 0.003*"currently" + 0.003*"important" + 0.003*"count" + 0.003*"map" + 0.002*"reuter" + 0.002*"region" + 0.002*"instead" + 0.002*"stand" + 0.002*"slow" + 0.002*"south_wale" + 0.002*"interact" + 0.002*"controversy" + 0.002*"breakthrough" + 0.002*"campaign" + 0.001*"epidemic" + 0.001*"week_period" + 0.001*"finally" + 0.001*"pop" + 0.001*"approach" + 0.001*"log" + 0.001*"gun" + 0.001*"significant" + 0.001*"previous" + 0.001*"race" + 0.001*"sar" + 0.001*"click" + 0.001*"auckland" + 0.001*"norm" + 0.001*"consecutive"')
(15, '0.167*"death" + 0.091*"die" + 0.056*"work" + 0.055*"news" + 0.041*"child" + 0.040*"surge" + 0.040*"week" + 0.027*"datum" + 0.025*"mask" + 0.019*"force" + 0.014*"far" + 0.010*"drop" + 0.009*"rally" + 0.009*"flu" + 0.009*"add" + 0.008*"condition" + 0.007*"worldwide" + 0.007*"share" + 0.006*"suffer" + 0.006*"minute" + 0.005*"remain" + 0.005*"easy" + 0.005*"western" + 0.005*"ago" + 0.005*"alone" + 0.005*"fda_expert" + 0.004*"represent" + 0.004*"investigate" + 0.004*"recently" + 0.004*"complication" + 0.003*"mind" + 0.003*"expose" + 0.003*"predict" + 0.003*"couple" + 0.003*"foxnew" + 0.003*"inequality" + 0.003*"past_hour" + 0.003*"gt" + 0.003*"others_injure" + 0.003*"analysis" + 0.003*"husband" + 0.002*"bear" + 0.002*"fox" + 0.002*"regularly" + 0.002*"tip" + 0.002*"vaccinat" + 0.002*"though" + 0.002*"hospitalisation" + 0.002*"hire" + 0.002*"contracting"')
(16, '0.092*"day" + 0.046*"county" + 0.031*"even" + 0.026*"booster_shot" + 0.023*"require" + 0.022*"unvaccinated" + 0.022*"ban" + 0.020*"huge" + 0.018*"close" + 0.018*"full" + 0.017*"exposure" + 0.015*"quarantine" + 0.014*"early" + 0.014*"beca" + 0.013*"teacher" + 0.012*"set" + 0.012*"pay" + 0.012*"reveal" + 0.011*"catch" + 0.011*"enough" + 0.011*"approval" + 0.010*"fauci_stresse" + 0.010*"nation" + 0.010*"house_spat" + 0.010*"tackle" + 0.009*"cover" + 0.009*"miss" + 0.009*"battle" + 0.008*"normal" + 0.007*"national" + 0.007*"implement" + 0.007*"summer" + 0.006*"complete" + 0.006*"restaurant" + 0.005*"solution" + 0.005*"fill" + 0.005*"straight" + 0.004*"together" + 0.004*"protest" + 0.004*"participant" + 0.004*"ease" + 0.004*"happy" + 0.004*"decide" + 0.004*"abortion" + 0.004*"austin" + 0.004*"judge" + 0.004*"tablet" + 0.003*"organize" + 0.003*"pill" + 0.003*"price"')
(17, '0.085*"take" + 0.051*"government" + 0.041*"high" + 0.029*"hospitalize" + 0.026*"treat" + 0.022*"lie" + 0.019*"lose" + 0.017*"hit" + 0.017*"medium" + 0.016*"fully_vaccinate" + 0.016*"likely" + 0.016*"affect" + 0.016*"ivermectin" + 0.015*"lead" + 0.015*"question" + 0.014*"woman" + 0.013*"train" + 0.011*"event" + 0.010*"tweet" + 0.010*"united_state" + 0.010*"develop" + 0.009*"mirror" + 0.007*"transmission" + 0.007*"demand" + 0.007*"opportunity" + 0.007*"mother" + 0.007*"responsible" + 0.007*"walk" + 0.007*"growth" + 0.007*"associate" + 0.006*"clinical_trial" + 0.006*"fix" + 0.006*"application" + 0.005*"endemic" + 0.005*"history" + 0.005*"crowd" + 0.005*"icu" + 0.004*"contain" + 0.004*"ppl" + 0.004*"remind" + 0.004*"quote" + 0.004*"toll" + 0.004*"chance" + 0.004*"short" + 0.004*"allegedly" + 0.004*"unproven" + 0.004*"exactly" + 0.004*"cash" + 0.004*"front" + 0.003*"healthcare"')
(18, '0.154*"say" + 0.133*"vaccination" + 0.034*"find" + 0.031*"also" + 0.027*"doctor" + 0.026*"study" + 0.020*"link" + 0.020*"testing" + 0.019*"daily" + 0.018*"story" + 0.018*"plan" + 0.015*"local" + 0.012*"offer" + 0.011*"large" + 0.011*"hold" + 0.011*"run" + 0.011*"rollout" + 0.010*"newsbreak" + 0.010*"system" + 0.009*"begin" + 0.007*"create" + 0.007*"las_vega" + 0.006*"target" + 0.006*"zealand_report" + 0.005*"proof" + 0.005*"interesting" + 0.005*"covidvaccine" + 0.005*"flight" + 0.004*"accuse" + 0.004*"bullshit" + 0.004*"deny" + 0.004*"obesity" + 0.004*"prepare" + 0.004*"hero_support" + 0.004*"rather" + 0.004*"quickly" + 0.003*"income" + 0.003*"plane" + 0.003*"avenger" + 0.003*"estimate" + 0.003*"exceed" + 0.003*"discuss" + 0.003*"refer" + 0.003*"clinical" + 0.003*"humanity" + 0.003*"portion" + 0.003*"reject" + 0.002*"parade" + 0.002*"briefing" + 0.002*"brady_confirm"')
(19, '0.082*"coronavirus" + 0.040*"insight" + 0.031*"increase" + 0.030*"variant" + 0.029*"active" + 0.024*"feel" + 0.024*"hear" + 0.023*"young" + 0.019*"impact" + 0.019*"expert" + 0.017*"turn" + 0.015*"warn" + 0.015*"population" + 0.014*"seem" + 0.013*"yesterday" + 0.013*"clinic" + 0.012*"actual" + 0.010*"resistance" + 0.010*"black" + 0.009*"fauci" + 0.008*"guess" + 0.008*"origin" + 0.007*"rampage" + 0.007*"florida_summ" + 0.007*"fresh" + 0.007*"piece" + 0.007*"adult" + 0.007*"hour" + 0.007*"sample" + 0.007*"name" + 0.006*"ahead" + 0.006*"citizen" + 0.006*"guardian" + 0.005*"girl" + 0.005*"one" + 0.005*"warm" + 0.005*"activity" + 0.005*"kind" + 0.005*"contribute" + 0.005*"latinos_remain" + 0.005*"racist" + 0.005*"tested_positive" + 0.005*"mu_variant" + 0.004*"smart" + 0.004*"form" + 0.004*"physical" + 0.004*"moment" + 0.004*"decimate" + 0.004*"trace" + 0.004*"sell"')

In [ ]:
doc_lda = lda_model[corpus]

In [ ]:
# Compute Perplexity
print('\nPerplexity: ', lda_model.log_perplexity(corpus))

Perplexity:  -9.655250938073756

In [ ]:
# Compute Coherence Score
from gensim.models import CoherenceModel# spaCy for preprocessing
coherence_model_lda = CoherenceModel(model=lda_model, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('\nCoherence Score: ', coherence_lda)

Coherence Score:  0.4135875416870716

In [ ]:
!pip3 install pyLDAvis==2.1.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyLDAvis==2.1.2
  Downloading pyLDAvis-2.1.2.tar.gz (1.6 MB)
     |████████████████████████████████| 1.6 MB 5.1 MB/s
Requirement already satisfied: wheel>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (0.37.1)
Requirement already satisfied: numpy>=1.9.2 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.21.6)
Requirement already satisfied: scipy>=0.18.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.7.3)
Requirement already satisfied: pandas>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.3.5)
Requirement already satisfied: joblib>=0.8.4 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.1.0)
Requirement already satisfied: jinja2>=2.7.2 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (2.11.3)
Requirement already satisfied: numexpr in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (2.8.3)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (3.6.4)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (0.16.0)
Collecting funcy
  Downloading funcy-1.17-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.7.2->pyLDAvis==2.1.2) (2.0.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.0->pyLDAvis==2.1.2) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.0->pyLDAvis==2.1.2) (2022.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.17.0->pyLDAvis==2.1.2) (1.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from numexpr->pyLDAvis==2.1.2) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->numexpr->pyLDAvis==2.1.2) (3.0.9)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (1.11.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (22.1.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (1.4.1)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (0.7.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (8.14.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (57.4.0)
Building wheels for collected packages: pyLDAvis
  Building wheel for pyLDAvis (setup.py) ... done
  Created wheel for pyLDAvis: filename=pyLDAvis-2.1.2-py2.py3-none-any.whl size=97738 sha256=2de19d75742db41d2307090d4aebc5c67089673db9d6e44e295d2aa2602a54d2
  Stored in directory: /root/.cache/pip/wheels/3b/fb/41/e32e5312da9f440d34c4eff0d2207b46dc9332a7b931ef1e89
Successfully built pyLDAvis
Installing collected packages: funcy, pyLDAvis
Successfully installed funcy-1.17 pyLDAvis-2.1.2

In [ ]:
# Visualize the topics
import pyLDAvis.gensim
#import pyLDAvis.gensim_models as gensimvis
pyLDAvis.enable_notebook()

vis = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
vis

/usr/local/lib/python3.7/dist-packages/past/types/oldstr.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
/usr/local/lib/python3.7/dist-packages/pyLDAvis/_prepare.py:232: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  head(R).drop('saliency', 1)

PreparedData(topic_coordinates=                  x         y  topics  cluster       Freq
topic
14     4.364153e-01  0.105392       1        1  11.678513
9      8.623327e-02 -0.415687       2        1   9.081365
5     -1.649618e-02  0.016582       3        1   5.420322
15    -1.641694e-02  0.011326       4        1   5.084653
8     -2.453360e-02  0.015269       5        1   4.839262
18    -2.536145e-02  0.013487       6        1   4.810268
1     -1.890428e-02  0.015708       7        1   4.686949
2     -2.736303e-02  0.022490       8        1   4.614570
4     -1.981817e-02  0.005830       9        1   4.543533
6     -3.242218e-02  0.015625      10        1   4.522160
0     -2.637609e-02  0.013693      11        1   4.483026
17    -3.046747e-02  0.017012      12        1   4.469067
10    -3.275930e-02  0.012338      13        1   4.285808
11    -3.673847e-02  0.024555      14        1   4.099490
7     -4.288850e-02  0.022338      15        1   4.098063
3     -6.752562e-08  0.005404      16        1   4.084056
16    -3.983459e-02  0.014907      17        1   4.083997
13    -4.526361e-02  0.026271      18        1   3.915363
19    -3.720846e-02  0.027808      19        1   3.786720
12    -4.979619e-02  0.029653      20        1   3.412816, topic_info=             Term          Freq         Total Category  logprob  loglift
5           covid  25276.000000  25276.000000  Default  30.0000  30.0000
19        vaccine   5727.000000   5727.000000  Default  29.0000  29.0000
4            case   6392.000000   6392.000000  Default  28.0000  28.0000
60         people   4312.000000   4312.000000  Default  27.0000  27.0000
14            get   3788.000000   3788.000000  Default  26.0000  26.0000
...           ...           ...           ...      ...      ...      ...
1195     diagnose    106.264412    107.121846  Topic20  -4.9699   3.3696
2220      realize    105.684037    106.541470  Topic20  -4.9753   3.3696
3214           sc    102.236629    103.094063  Topic20  -5.0085   3.3693
51        failure     99.040163     99.897596  Topic20  -5.0403   3.3690
2638  daily_thank     98.808027     99.665460  Topic20  -5.0426   3.3690

[646 rows x 6 columns], token_table=      Topic      Freq            Term
term
1883      9  0.990926            able
1905      9  0.991963          access
866      16  0.990371          accord
5243      6  0.992584          accuse
121       5  0.996476             act
...     ...       ...             ...
435       2  0.999069            year
76       19  0.995053       yesterday
439       7  0.992586             yet
785      19  0.998701           young
1519      6  0.991968  zealand_report

[720 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[15, 10, 6, 16, 9, 19, 2, 3, 5, 7, 1, 18, 11, 12, 8, 4, 17, 14, 20, 13])

In [ ]:
pyLDAvis.save_html(vis, '2021_lda.html')

In [ ]:
!unzip "/content/mallet-2.0.8.zip"

In [ ]:
mallet_path = '/content/mallet-2.0.8/bin/mallet' # update this path
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, 
                                             corpus=corpus, 
                                             num_topics=20,
                                             id2word=id2word,
                                             iterations=1000,
                                             optimize_interval=10)

/usr/local/lib/python3.7/dist-packages/smart_open/smart_open_lib.py:494: DeprecationWarning: This function is deprecated.  See https://github.com/RaRe-Technologies/smart_open/blob/develop/MIGRATING_FROM_OLDER_VERSIONS.rst for more information
  warnings.warn(message, category=DeprecationWarning)
/usr/local/lib/python3.7/dist-packages/smart_open/smart_open_lib.py:494: DeprecationWarning: This function is deprecated.  See https://github.com/RaRe-Technologies/smart_open/blob/develop/MIGRATING_FROM_OLDER_VERSIONS.rst for more information
  warnings.warn(message, category=DeprecationWarning)

In [ ]:
pprint(ldamallet.show_topics(num_topics=20,num_words=100,formatted=False))

# Compute Coherence Score
coherence_model_ldamallet = CoherenceModel(model=ldamallet, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
coherence_ldamallet = coherence_model_ldamallet.get_coherence()

print('\n Coherence Score: ', round(coherence_ldamallet, 2))

[(0,
  [('world', 0.042105263157894736),
   ('home', 0.0374384236453202),
   ('covid', 0.03634949442571947),
   ('pandemic', 0.022919367383977183),
   ('drug', 0.02229712211563391),
   ('free', 0.02079336271713767),
   ('lead', 0.01944516463572725),
   ('testing', 0.019134042001555614),
   ('turn', 0.018148820326678767),
   ('restriction', 0.017422867513611617),
   ('reason', 0.014570910033704951),
   ('booster_shot', 0.014311641171895255),
   ('provide', 0.014000518537723619),
   ('stay', 0.013844957220637801),
   ('base', 0.01322271195229453),
   ('event', 0.01151153746435053),
   ('site', 0.009904070521130412),
   ('nobel_prize', 0.008970702618615505),
   ('education', 0.008296603577910292),
   ('keep_tab', 0.007052113041223749),
   ('grow', 0.0070002592688618095),
   ('employees_worke', 0.0070002592688618095),
   ('small', 0.00694840549649987),
   ('part', 0.006844697951775992),
   ('choice', 0.006844697951775992),
   ('nation', 0.006844697951775992),
   ('recommend', 0.006740990407052113),
   ('lack', 0.006429867772880477),
   ('idea', 0.006378014000518538),
   ('detail', 0.006170598911070781),
   ('honoured_distinction', 0.006170598911070781),
   ('access', 0.006066891366346902),
   ('major', 0.006015037593984963),
   ('history', 0.0059631838216230235),
   ('fda_approval', 0.005859476276899144),
   ('ivermectin_multifacete', 0.005755768732175265),
   ('fund', 0.005755768732175265),
   ('step', 0.0056002074150894475),
   ('notice', 0.005081669691470054),
   ('sound', 0.004770547057298419),
   ('technology', 0.004718693284936479),
   ('corona', 0.00466683951257454),
   ('effect', 0.00466683951257454),
   ('surpass', 0.004511278195488722),
   ('ease', 0.004459424423126783),
   ('resource', 0.004355716878402904),
   ('win', 0.004303863106040965),
   ('fauci_stresse', 0.004148301788955146),
   ('foxnew', 0.0040445942442312675),
   ('opinion', 0.0037853253824215714),
   ('project', 0.0037334716100596316),
   ('fly', 0.0037334716100596316),
   ('indicated_efficacy', 0.0035260565206118744),
   ('grant', 0.003474202748249935),
   ('stress', 0.003422348975887996),
   ('stuff', 0.003422348975887996),
   ('disaster', 0.003318641431164117),
   ('doubt', 0.003318641431164117),
   ('wh', 0.003318641431164117),
   ('eye', 0.003318641431164117),
   ('smart', 0.003318641431164117),
   ('ppl', 0.003266787658802178),
   ('global_sc', 0.0032149338864402386),
   ('town', 0.0032149338864402386),
   ('cov', 0.00311122634171636),
   ('prime_minister', 0.0029038112522686023),
   ('food', 0.0029038112522686023),
   ('therapeutic', 0.0028001037075447237),
   ('seek', 0.0027482499351827844),
   ('fda_approve', 0.0027482499351827844),
   ('lung', 0.002696396162820845),
   ('brother', 0.002696396162820845),
   ('meeting', 0.002696396162820845),
   ('budget', 0.0025926886180969665),
   ('alive', 0.002540834845735027),
   ('thehill', 0.002540834845735027),
   ('blow', 0.002488981073373088),
   ('fit', 0.002488981073373088),
   ('flow', 0.002488981073373088),
   ('recall', 0.0024371273010111486),
   ('xe', 0.0023852735286492093),
   ('vaxe', 0.0023852735286492093),
   ('developed_countrie', 0.0023852735286492093),
   ('refer', 0.0022815659839253307),
   ('operate', 0.0022815659839253307),
   ('transmit', 0.0022815659839253307),
   ('accurate', 0.0022815659839253307),
   ('series', 0.0022815659839253307),
   ('parasite', 0.002177858439201452),
   ('house', 0.002074150894477573),
   ('simply', 0.002074150894477573),
   ('view', 0.0020222971221156337),
   ('ticket', 0.0019704433497536944),
   ('living', 0.0019185895773917553),
   ('ship', 0.0019185895773917553),
   ('senior', 0.0019185895773917553),
   ('super_spreader', 0.0019185895773917553),
   ('charity', 0.0019185895773917553),
   ('half', 0.0017630282603059372),
   ('nursing', 0.0017630282603059372)]),
 (1,
  [('pandemic', 0.0641735918744229),
   ('covid', 0.05940289319790705),
   ('spread', 0.04704011490715092),
   ('stop', 0.04329537293526213),
   ('risk', 0.04319277726479943),
   ('late', 0.03842207858828357),
   ('business', 0.019698368728839642),
   ('play', 0.01713347696727198),
   ('sick', 0.015594541910331383),
   ('increase', 0.012567969631681544),
   ('healthcare_worker', 0.01220888478506207),
   ('group', 0.011798502103211244),
   ('act', 0.010208269211039294),
   ('million', 0.010156971375807941),
   ('city', 0.009541397353031703),
   ('misinformation', 0.00933620601210629),
   ('global', 0.00887452549502411),
   ('urge', 0.007848568790397045),
   ('challenge', 0.0073355904380835125),
   ('ban', 0.007232994767620807),
   ('transmission', 0.007079101261926747),
   ('benefit', 0.007079101261926747),
   ('resident', 0.0068739099210013335),
   ('surge_pose', 0.006771314250538628),
   ('center', 0.006720016415307274),
   ('issue', 0.006720016415307274),
   ('daily_thank', 0.006668718580075921),
   ('message', 0.006309633733456448),
   ('card', 0.006309633733456448),
   ('fight', 0.005950548886836975),
   ('role', 0.005283677028829383),
   ('healthcare', 0.0050784856879039705),
   ('avoid', 0.005027187852672617),
   ('radio', 0.004975890017441264),
   ('ptsd', 0.004719400841284498),
   ('social', 0.004719400841284498),
   ('eat', 0.0044629116651277315),
   ('survey', 0.004411613829896378),
   ('crowd', 0.0043090181594336715),
   ('approach', 0.0040012311480455524),
   ('international', 0.003847337642351493),
   ('economic', 0.00364214630142608),
   ('improve', 0.0035395506309633734),
   ('importance', 0.0035395506309633734),
   ('region', 0.00348825279573202),
   ('leaders_faile', 0.0033343592900379605),
   ('period', 0.003283061454806607),
   ('development', 0.003283061454806607),
   ('large', 0.0031804657843439005),
   ('decrease', 0.0031804657843439005),
   ('jump', 0.0031291679491125476),
   ('students_quarantine', 0.0030778701138811943),
   ('tune', 0.0030778701138811943),
   ('white', 0.003026572278649841),
   ('tyranny', 0.0029752744434184877),
   ('person', 0.0029239766081871343),
   ('manage', 0.0029239766081871343),
   ('growth', 0.0029239766081871343),
   ('agency', 0.0028726787729557814),
   ('debate', 0.002821380937724428),
   ('practice', 0.002821380937724428),
   ('aim', 0.002770083102493075),
   ('financial', 0.0027187852672617215),
   ('space', 0.002667487432030368),
   ('goal', 0.002564891761567662),
   ('criminal', 0.002564891761567662),
   ('tired', 0.002564891761567662),
   ('tax', 0.002410998255873602),
   ('safety_net', 0.0022571047501795424),
   ('pretend', 0.0022571047501795424),
   ('religious', 0.0021545090797168358),
   ('medical_regulator', 0.0020519134092541295),
   ('assistance', 0.0020519134092541295),
   ('professional', 0.0020519134092541295),
   ('african_affair', 0.0020519134092541295),
   ('violence', 0.0020006155740227762),
   ('connect', 0.0020006155740227762),
   ('boost', 0.001949317738791423),
   ('ending_affecte', 0.0018980199035600698),
   ('platform', 0.0018980199035600698),
   ('dude', 0.0018980199035600698),
   ('officially', 0.0018980199035600698),
   ('anchor', 0.0018980199035600698),
   ('fast', 0.0018467220683287165),
   ('manager', 0.0018467220683287165),
   ('judge', 0.0018467220683287165),
   ('zone', 0.0018467220683287165),
   ('mid', 0.0018467220683287165),
   ('migrant', 0.0018467220683287165),
   ('airborne', 0.0018467220683287165),
   ('tour', 0.0017954242330973634),
   ('dismiss', 0.0017954242330973634),
   ('saturday_broadcast', 0.0017954242330973634),
   ('outcome', 0.0017954242330973634),
   ('elderly', 0.001692828562634657),
   ('significantly', 0.0016415307274033036),
   ('praise', 0.0016415307274033036),
   ('pose', 0.0015902328921719503),
   ('cloth_mask', 0.0015902328921719503),
   ('machine', 0.0015902328921719503)]),
 (2,
  [('coronavirus', 0.1019836022216345),
   ('month', 0.03327162126421582),
   ('story', 0.026448029621793177),
   ('sign', 0.02348585030415234),
   ('back', 0.02338005818566517),
   ('hope', 0.02189896852684475),
   ('outbreak', 0.02147580005289606),
   ('late', 0.018513620735255223),
   ('share', 0.018143348320550118),
   ('contract', 0.0166622586617297),
   ('staff', 0.016344882306268183),
   ('service', 0.014599312351229833),
   ('pm', 0.014123247818037556),
   ('fall', 0.013594287225601692),
   ('change', 0.012324781803755621),
   ('hold', 0.012271885744512033),
   ('experience', 0.011055276381909548),
   ('jab', 0.010949484263422375),
   ('covid', 0.010473419730230098),
   ('public_inquiry', 0.010208939434012167),
   ('petition_calle', 0.010103147315524993),
   ('uk_response', 0.010050251256281407),
   ('outbreak_sign', 0.009468394604601957),
   ('fear', 0.00899233007140968),
   ('drop', 0.00856916159746099),
   ('reveal', 0.008463369478973817),
   ('law', 0.007564136471832849),
   ('info', 0.007564136471832849),
   ('interest', 0.006400423168473949),
   ('join', 0.006294631049986776),
   ('contact', 0.0061888389314996035),
   ('offer', 0.006135942872256017),
   ('parade', 0.006083046813012431),
   ('brady_reveal', 0.005554086220576567),
   ('petition', 0.0054482941020893945),
   ('shortly', 0.004601957154192013),
   ('bad', 0.004549061094948426),
   ('location', 0.004443268976461253),
   ('mutation', 0.004125892620999736),
   ('joke', 0.004125892620999736),
   ('carry', 0.004072996561756149),
   ('diagnose', 0.0038614123247818037),
   ('resistance', 0.0036498280878074583),
   ('buccaneers_super', 0.003596932028563872),
   ('room', 0.0035440359693202856),
   ('significant', 0.003491139910076699),
   ('restaurant', 0.003438243850833113),
   ('picture', 0.00333245173234594),
   ('sale', 0.00333245173234594),
   ('legal', 0.0032266596138587674),
   ('church', 0.0031208674953715947),
   ('art', 0.0031208674953715947),
   ('hesitancy', 0.0031208674953715947),
   ('victory', 0.003015075376884422),
   ('commit', 0.0029621793176408356),
   ('force', 0.0029621793176408356),
   ('cry', 0.002856387199153663),
   ('music', 0.0028034911399100765),
   ('rampage', 0.0028034911399100765),
   ('reporting', 0.0028034911399100765),
   ('power', 0.002697699021422904),
   ('massive', 0.0026448029621793175),
   ('visitor', 0.002591906902935731),
   ('definition', 0.0025390108436921448),
   ('accuse', 0.0025390108436921448),
   ('florida_summ', 0.0025390108436921448),
   ('abortion', 0.0024861147844485584),
   ('stay_safe', 0.002433218725204972),
   ('hotel', 0.002433218725204972),
   ('feature', 0.0023803226659613857),
   ('celebration', 0.002274530547474213),
   ('bar', 0.0022216344882306266),
   ('could_affect', 0.0022216344882306266),
   ('yo', 0.0021687384289870403),
   ('virtual', 0.0021158423697434543),
   ('forever', 0.0020100502512562816),
   ('ad', 0.0020100502512562816),
   ('blog', 0.0020100502512562816),
   ('email', 0.0019571541920126953),
   ('wit', 0.0019571541920126953),
   ('sky', 0.0019571541920126953),
   ('brink', 0.0019042581327691087),
   ('following_buccaneer', 0.0019042581327691087),
   ('include', 0.0019042581327691087),
   ('delay', 0.0018513620735255223),
   ('afraid', 0.001798466014281936),
   ('pregnant_woman', 0.001798466014281936),
   ('perform', 0.001798466014281936),
   ('operation', 0.001798466014281936),
   ('wild', 0.001798466014281936),
   ('washington_post', 0.0017455699550383496),
   ('forward', 0.0016926738957947632),
   ('york_time', 0.0016926738957947632),
   ('lay', 0.0016397778365511769),
   ('excellent', 0.0016397778365511769),
   ('proud', 0.0016397778365511769),
   ('arm', 0.0015868817773075905),
   ('natural', 0.0015339857180640042),
   ('artist', 0.0015339857180640042),
   ('africanunion', 0.0015339857180640042)]),
 (3,
  [('health', 0.07378849001685135),
   ('hospital', 0.057856303937088294),
   ('patient', 0.04258795894398203),
   ('care', 0.03921768881172445),
   ('student', 0.03635806566920288),
   ('surge', 0.03620487157228208),
   ('treatment', 0.02813664913445335),
   ('worker', 0.02052800898738702),
   ('vaccinate', 0.02047694428841342),
   ('unvaccinated', 0.019608844405862226),
   ('sh', 0.014961956799264669),
   ('oxygen', 0.014093856916713476),
   ('covid', 0.013889598120819078),
   ('tackle', 0.01368533932492468),
   ('full', 0.01363427462595108),
   ('safety', 0.01363427462595108),
   ('firefight_erupte', 0.013174692335188684),
   ('send', 0.012868304141347087),
   ('latter_fire', 0.012766174743399888),
   ('sri_lanka', 0.012612980646479088),
   ('release', 0.011949139559822295),
   ('sends_tonne', 0.011540621968033498),
   ('authority', 0.010161875095746311),
   ('quarantine', 0.009957616299851913),
   ('protocol', 0.009753357503957514),
   ('emergency', 0.00791502834090793),
   ('bed', 0.007608640147066333),
   ('choose', 0.007149057856303937),
   ('admit', 0.00679160496348874),
   ('medicine', 0.006383087371699944),
   ('guideline', 0.005872440381963948),
   ('critical', 0.0058213756829903485),
   ('survive', 0.005463922790175152),
   ('cancer', 0.005412858091201552),
   ('capacity', 0.005259663994280754),
   ('fill', 0.005055405198386356),
   ('condition', 0.00454475820865036),
   ('strike', 0.004493693509676761),
   ('idiot', 0.004391564111729561),
   ('prevention', 0.0038809171219935656),
   ('diagnosis', 0.0038809171219935656),
   ('classroom', 0.0037787877240463667),
   ('implement', 0.0035745289281519685),
   ('unit', 0.0034723995302047696),
   ('stadium', 0.00342133483123117),
   ('ventilator', 0.003217076035336772),
   ('defeat', 0.0030128172394423736),
   ('unvaccinate', 0.0028596231425215748),
   ('therapy', 0.0028596231425215748),
   ('promotion', 0.0028085584435479753),
   ('essential', 0.002757493744574376),
   ('vaccinated', 0.002706429045600776),
   ('physician', 0.0026553643466271765),
   ('manage', 0.0026553643466271765),
   ('priority', 0.0026553643466271765),
   ('frontline', 0.0026553643466271765),
   ('teacherstudent_feel', 0.0026553643466271765),
   ('yesterday', 0.0026553643466271765),
   ('internet_globally', 0.002604299647653577),
   ('letter', 0.0024511055507327783),
   ('contracting', 0.0024511055507327783),
   ('pack', 0.002400040851759179),
   ('director', 0.0023489761527855793),
   ('overwhelm', 0.0023489761527855793),
   ('pediatric', 0.00229791145381198),
   ('hawaii', 0.00229791145381198),
   ('surgery', 0.00229791145381198),
   ('want_general', 0.0022468467548383804),
   ('like_focuse', 0.0021957820558647805),
   ('strict', 0.0021957820558647805),
   ('weak_due', 0.0021957820558647805),
   ('realise', 0.0020936526579175816),
   ('involve', 0.0020936526579175816),
   ('partner', 0.0019915232599703823),
   ('overdose', 0.0019915232599703823),
   ('roll', 0.0017872644640759842),
   ('wa', 0.0017361997651023848),
   ('coronaviru', 0.0017361997651023848),
   ('monoclonal_antibodie', 0.001685135066128785),
   ('leave', 0.0016340703671551856),
   ('worsen', 0.001583005668181586),
   ('winter', 0.001583005668181586),
   ('green', 0.0015319409692079865),
   ('mom', 0.0015319409692079865),
   ('wife_release', 0.0015319409692079865),
   ('admission', 0.001480876270234387),
   ('temporary', 0.0014298115712607874),
   ('pneumonia', 0.001378746872287188),
   ('suspend', 0.001378746872287188),
   ('urgent', 0.001378746872287188),
   ('weight', 0.001378746872287188),
   ('occupy', 0.001378746872287188),
   ('interrupt', 0.0013276821733135883),
   ('icu', 0.0013276821733135883),
   ('milk', 0.0013276821733135883),
   ('icu_capacity', 0.0013276821733135883),
   ('hospitals_crushe', 0.0013276821733135883),
   ('seek', 0.0013276821733135883),
   ('overseas', 0.0013276821733135883),
   ('potentially', 0.0012255527753663891)]),
 (4,
  [('people', 0.09618454250553525),
   ('virus', 0.04932804695947685),
   ('good', 0.033571906698934145),
   ('lockdown', 0.028165387982081253),
   ('family', 0.028062406673188815),
   ('lose', 0.020596261778487203),
   ('disease', 0.018845579527315793),
   ('hit', 0.016991915967251945),
   ('fact', 0.016168065496112455),
   ('catch', 0.013542042119355337),
   ('begin', 0.0134390608104629),
   ('fight', 0.0134390608104629),
   ('leave', 0.013130116883785592),
   ('hard', 0.012821172957108285),
   ('job', 0.012357757067092323),
   ('tested_positive', 0.011945831831522579),
   ('political', 0.01163688790484527),
   ('tweet', 0.011533906595952834),
   ('friend', 0.010967509397044436),
   ('pass', 0.01060707481592091),
   ('stupid', 0.01034962154368982),
   ('heart', 0.008856392564749498),
   ('deadly', 0.008135523402502445),
   ('black', 0.007157200968024304),
   ('morning', 0.007105710313578086),
   ('struggle', 0.0064878224602234694),
   ('head', 0.0064878224602234694),
   ('loss', 0.006178878533546162),
   ('baby', 0.006178878533546162),
   ('covidiot', 0.005972915915761289),
   ('animal', 0.005818443952422635),
   ('anti', 0.005715462643530199),
   ('beat', 0.005509500025745327),
   ('buy', 0.005355028062406673),
   ('change', 0.005200556099068019),
   ('threaten', 0.004994593481283147),
   ('shortage', 0.004994593481283147),
   ('hate', 0.004994593481283147),
   ('mind', 0.004943102826836929),
   ('boy', 0.004840121517944493),
   ('finally', 0.004840121517944493),
   ('kind', 0.004840121517944493),
   ('lift', 0.004634158900159621),
   ('meet', 0.004531177591267185),
   ('mass', 0.004479686936820967),
   ('type', 0.004376705627928531),
   ('scientific', 0.004273724319036095),
   ('epidemic', 0.004222233664589877),
   ('cold', 0.004170743010143659),
   ('scare', 0.004119252355697441),
   ('statement', 0.004119252355697441),
   ('dog', 0.003861799083466351),
   ('complication', 0.003604345811235261),
   ('attack', 0.0035013645023428248),
   ('gain', 0.0035013645023428248),
   ('lock', 0.0033983831934503886),
   ('hurt', 0.003295401884557953),
   ('evil', 0.0031924205756655166),
   ('philippine', 0.0031924205756655166),
   ('design', 0.0030379486123268628),
   ('mutate', 0.0028834766489882085),
   ('multiple', 0.002831985994541991),
   ('shame', 0.0027804953400957727),
   ('daughter', 0.0027804953400957727),
   ('token', 0.0025745327223109004),
   ('occur', 0.0025230420678646827),
   ('era', 0.0024200607589722465),
   ('survivor', 0.0024200607589722465),
   ('idiot', 0.0023170794500798103),
   ('round', 0.0022655887956335927),
   ('hundred', 0.0022655887956335927),
   ('gather', 0.0022655887956335927),
   ('deep', 0.0022140981411873746),
   ('aware', 0.0022140981411873746),
   ('vaxxed', 0.0021626074867411565),
   ('cat', 0.0021626074867411565),
   ('planning', 0.0021111168322949384),
   ('mom', 0.0021111168322949384),
   ('fault', 0.0020596261778487203),
   ('dewormer', 0.0020081355234025026),
   ('origins_trace', 0.0020081355234025026),
   ('winter', 0.0019566448689562845),
   ('cool', 0.0019566448689562845),
   ('night', 0.0019566448689562845),
   ('thi', 0.0019051542145100664),
   ('original', 0.0018536635600638483),
   ('reading', 0.0018536635600638483),
   ('income', 0.0018021729056176305),
   ('convince', 0.0017506822511714124),
   ('son', 0.0017506822511714124),
   ('nonsense', 0.0017506822511714124),
   ('travel_ban', 0.0016991915967251943),
   ('suicide', 0.0016991915967251943),
   ('life', 0.0016991915967251943),
   ('reply', 0.0016991915967251943),
   ('british', 0.0016991915967251943),
   ('miss', 0.0015962102878327583),
   ('truth', 0.0015447196333865404),
   ('brady_confirm', 0.0014932289789403223),
   ('unemployment', 0.0014932289789403223)]),
 (5,
  [('covid', 0.14792746113989638),
   ('show', 0.04077720207253886),
   ('study', 0.03507772020725389),
   ('datum', 0.032590673575129535),
   ('infection', 0.02373056994818653),
   ('place', 0.018911917098445596),
   ('link', 0.017409326424870468),
   ('break', 0.016891191709844558),
   ('reduce', 0.0138860103626943),
   ('post', 0.013264248704663213),
   ('set', 0.012849740932642488),
   ('recover', 0.012383419689119171),
   ('push', 0.010932642487046632),
   ('leader', 0.009948186528497409),
   ('cure', 0.008911917098445596),
   ('top', 0.008756476683937824),
   ('figure', 0.008704663212435234),
   ('yesterday', 0.008445595854922279),
   ('suggest', 0.007979274611398964),
   ('reach', 0.00772020725388601),
   ('true', 0.007202072538860104),
   ('border', 0.007202072538860104),
   ('trial', 0.007202072538860104),

In [ ]:
mallet_lda_model = gensim.models.wrappers.ldamallet.malletmodel2ldamodel(ldamallet)

In [ ]:
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(mallet_lda_model, corpus, id2word,sort_topics=False)

/usr/local/lib/python3.7/dist-packages/pyLDAvis/_prepare.py:232: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  head(R).drop('saliency', 1)

In [ ]:
print(vis.topic_order)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
pyLDAvis.save_html(vis, '2021_lda_mallet.html')

In [ ]:
vis

PreparedData(topic_coordinates=                  x         y  topics  cluster      Freq
topic
0      9.297136e-07 -0.000331       1        1  4.995213
1      8.825777e-05  0.000287       2        1  5.003269
2      9.972338e-05 -0.000118       3        1  4.968373
3      6.051582e-05  0.000694       4        1  4.996484
4     -4.836025e-04 -0.000078       5        1  5.011082
5     -1.522392e-04 -0.000315       6        1  4.994903
6      1.886958e-04  0.000357       7        1  5.091743
7      2.331085e-04  0.000171       8        1  4.993255
8     -1.920329e-04 -0.000152       9        1  5.004622
9      1.244929e-04  0.000099      10        1  4.984925
10     2.745039e-04  0.000760      11        1  5.019357
11    -1.169057e-04 -0.000583      12        1  5.012972
12     4.320524e-06  0.000007      13        1  4.982893
13     1.881813e-04 -0.000135      14        1  5.004517
14     7.688951e-04 -0.000213      15        1  5.000383
15     1.045390e-04 -0.000302      16        1  5.006071
16    -4.319554e-04 -0.000526      17        1  4.986514
17    -2.678491e-04  0.000490      18        1  5.000304
18     5.483668e-04 -0.000352      19        1  4.975376
19    -1.039946e-03  0.000239      20        1  4.967742, topic_info=                 Term       Freq      Total Category  logprob  loglift
9740          takaful  15.000000  15.000000  Default  30.0000  30.0000
17790   brexitreality  15.000000  15.000000  Default  29.0000  29.0000
5164   northernbeache  15.000000  15.000000  Default  28.0000  28.0000
22845            redu  15.000000  15.000000  Default  27.0000  27.0000
19846             adj  16.000000  16.000000  Default  26.0000  26.0000
...               ...        ...        ...      ...      ...      ...
8481         dialogue   1.039384  16.526634  Topic20  -9.9726   0.2359
10298             spd   1.033981  16.100849  Topic20  -9.9778   0.2567
16474   misgovernance   1.031580  16.005861  Topic20  -9.9801   0.2603
27225          pourri   1.030358  15.989874  Topic20  -9.9813   0.2602
17392           ehite   1.030436  16.160740  Topic20  -9.9812   0.2496

[857 rows x 6 columns], token_table=       Topic      Freq     Term
term
16784      1  0.062294   abcent
16784      2  0.062294   abcent
16784      3  0.062294   abcent
16784      4  0.062294   abcent
16784      5  0.062294   abcent
...      ...       ...      ...
21101     16  0.062965  zwergie
21101     17  0.062965  zwergie
21101     18  0.062965  zwergie
21101     19  0.062965  zwergie
21101     20  0.062965  zwergie

[16679 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])